### ISSUE TITLE
API for the web version of Sabaki?

### ISSUE THREAD

**Issue by crodgers** [yishn/Sabaki#112]
Is there documentation for the API to the web version of Sabaki? I'd love to use it in some projects I am working on, but need the ability to manipulate the board directly. 

i.e.
`sabakiGame.playAt(1, 2);`
`sabakiGame.undo();`

**Comment by yishn** [comment]
There is no documentation yet. I can give you some pointers where to look at. The easiest way to make a move is to use the global function `makeMove(vertex)` where vertex is an array `[x, y]` or `[-1, -1]` for pass. The color is determined automatically (as indicated in the bottom bar).

You can navigate the game tree by using `goBack()`, `goForward()`, `goToBeginning()`, `goToEnd()`, etc...

Other global functions related to functionality are defined in `view/index.js`. Global functions for changing the view are defined in `view/index.view.js`.

The code is sadly a little bit all over the place and not very developer friendly as it was not designed that way. I should probably take the time and create a better API.
