### ISSUE TITLE
GTP console behaves weirdly on Mac with native overlay scrollbars turned on

### ISSUE THREAD

**Issue by pelmers** [yishn/Sabaki#113]
As the title states, I do not see a way to scroll the GTP console. When it overflows, the board flies up up and away leaving me with a black screen. I must clear the console before it comes back.
<img width="1258" alt="picture" src="https://cloud.githubusercontent.com/assets/2406051/16749431/fb021d8c-477e-11e6-91d7-1c025dd9431c.png">

**Comment by yishn** [comment]
It works fine here on Windows 10. Can you tell me the OS you're using and the version of Sabaki?

**Comment by pelmers** [comment]
I downloaded v0.16.0 from the release page and run on OS X.

**Comment by yishn** [comment]
Ok, I've done some research. This is only happening if you have overlay scrollbars turned on. For the meantime, turn overlay scrollbars off (Set 'Show scrollbars' to 'Always').
