### ISSUE TITLE
setting first player

### ISSUE THREAD

**Issue by georgemarrow** [yishn/Sabaki#115]
Hi,

Is there a way to set the first player after editing a position? Right now it seems that only Black can play first. I use it to edit problems, and I have been removing the pass manually when White goes first.

On a related note, would you consider allowing one to set the PL tag?

Thanks

**Comment by yishn** [comment]
That's a great idea! Do you have some suggestions as how to let the user set the `PL` tag? Maybe in edit mode on the edit bar? Or somewhere else?

**Comment by georgemarrow** [comment]
Well, I think the only place one would need to set PL is on the root node (game properties). As such, while it can definitely be in the edit mode, it may needlessly clutter that interface. I like the edit mode simplicity as it is right now.

**Comment by fohristiwhirl** [comment]
I note that PL tags that already exist are not honoured at the moment. Strictly speaking any node should be able to have a PL tag, which would override whatever logic Sabaki uses to determine whose move it is.

**Comment by yishn** [comment]
I don't think `PL` is root node only. It's a 'setup property' along with `AE`, `AW` and `AB` (see [spec](http://www.red-bean.com/sgf/properties.html#PL)), so one should be able to set it on any node.

**Comment by yishn** [comment]
@fohristiwhirl: Sabaki should honor existing `PL` tags. Checking... Hm, `PL[W]` is working, but `PL[B]` is not. This is a bug.

**Comment by georgemarrow** [comment]
Okay then, the edit mode seems like the appropriate place if you wanna retain the full generality of the spec.

**Comment by yishn** [comment]
Another idea is to repurpose the current player indicator:

![Current player indicator](https://cloud.githubusercontent.com/assets/9217349/17462344/1b546a8c-5caa-11e6-94ac-9227af795807.png)

Currently, clicking the indicator will make a pass (and thus switching the player). Instead, we can just change the player (adding `PL` tag if necessary) without making a pass.

**Comment by georgemarrow** [comment]
I find that a bit unexpected and therefore likely to confuse. If I understand correctly, you propose to modify the play-like mode: each click corresponds to making a move --- either placing a valid color stone in a valid position or pass. While I remember wondering how to pass the first time (clicking on the player indicator did not strike me as the way to play pass), I don't think changing the meaning of the indicator click to inserting a `PL` (which is not a game event, but rather  something that goes against the natural development of the game or the implementation of different rules) would improve upon the matter. Besides, how will one generate a pass then? Use a click modifier (ex. Ctrl-click) on the same button? Add another button? I think that would be a bit opaque to the user: even though the situation on the board would look the same the generated SGF will be different, and it may trigger a different treatment in another SGF consumer (different semantics).

**Comment by yishn** [comment]
I think we have a misunderstanding.

The (intended) way to make a pass is to click on the hamburger menu and choose 'Pass'. The click on the current player indicator is just a shortcut if you will. I'm not suggesting to completely replace passing!

My thoughts are as follows: If the current player indicator is clickable, one would expect it to change the current player. Currently, Sabaki interprets this as 'Make a pass'. But I think it would be even more natural to insert a `PL` tag instead. (Change current board state instead of creating a new node)

Nevertheless, I agree that suddenly changing the behavior is a breaking change and probably a bad idea. What are your thoughts on this?

**Comment by apetresc** [comment]
I'm not @georgemarrow but I completely agree with your suggestion: making a pass is semantically very different from setting `PL`, and forcing the current player indicator represents the latter much more than the former.

Here's one compelling UX argument: everything about the current player indicator represents a toggle, so you would expect that hitting it twice returns you to the exact same state you were in. But – whoops! – if you try to do that, you'll be prompted to remove dead stones. In fact, if you hit the current player indicator by accident, you have to go all the way to the tree view to undo that. This completely breaks expectation for that kind of UI element. However, if it simple toggled `PL`, it would behave the way you'd expect.

My $0.02!

**Comment by georgemarrow** [comment]
@yishn  I see now what you meant. I think it would be a welcome change that would align better the present icon with the button semantics, as @apetresc also pointed out. I am not sure about delegating the pass to the right-side menu only, but I think your suggestion as stated is an improvement.

**Comment by apetresc** [comment]
If the goal is to still have a convenient way to input a pass move, how about adding a shortcut for it? (Unless I'm missing one that already exists). ⌘P or something.

**Comment by yishn** [comment]
I can add a keyboard shortcut for that. Thanks for your input everybody!
