### ISSUE TITLE
Engines do not honor system paths in OS X

### ISSUE THREAD

**Issue by soma-six** [yishn/Sabaki#117]
GnuGo 3.8 and BetaGo both report "connection error",
and I tested both Engines without Sabaki and they are in working order.

**Comment by yishn** [comment]
Make sure the engines are in GTP mode. GNU Go needs the arguments `--mode gtp` to work.

**Comment by soma-six** [comment]
by "without Sabaki" I meant I tested them both in terminal, in GTP mode.

**Comment by yishn** [comment]
GNU Go 3.8 is working fine here on Windows. Which OS do you use? What version of Sabaki do you use? Can you post the engine data for both GNU Go and BetaGo?

**Comment by soma-six** [comment]
OS X El Capitan (10.11.6) Sabaki (0.17.0)

Please define Engine Data

**Comment by yishn** [comment]
I'd like you to make a screenshot of Sabaki when you go into 'Preferences' > 'Engines' tab. Make sure GNU Go and BetaGo are visible.

**Comment by soma-six** [comment]
![screen shot 2016-08-12 at 4 09 01 am](https://cloud.githubusercontent.com/assets/17106913/17619472/d1484ca0-6042-11e6-81fa-4942a3b66bf7.png)

**Comment by soma-six** [comment]
![screen shot 2016-08-12 at 4 13 41 am](https://cloud.githubusercontent.com/assets/17106913/17619540/2f0cd40a-6043-11e6-8fd7-6fbaef57e2aa.png)

**Comment by soma-six** [comment]
![screen shot 2016-08-12 at 4 20 03 am](https://cloud.githubusercontent.com/assets/17106913/17619663/191e5460-6044-11e6-83b0-66c65fea71bc.png)

**Comment by yishn** [comment]
As for BetaGo, I think it should point to python with the `.py` file as argument. As for GNU Go, can you try using the full path?

**Comment by soma-six** [comment]
It's in my path so technically it should make no difference. But sure why not

**Comment by soma-six** [comment]
Thanks so much for the help! Should've tried the full path by myself though.. oh well.
GnuGo 3.8 is working!!!
and I'm modifying BetaGo to work now.
You should check it out, it's an AlphaGo fork essentially, create your own bots to play against.
I'm going to try and create entities like Seigen trained off their games alone, so maybe I can play the dead.

**Comment by yishn** [comment]
I see, so Sabaki seems to not honor system paths on OS X. That's weird, as it works under Windows; that may be a bug of node, I'll investigate further. Thanks for the help, I'll definitely check out BetaGo!
