### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by georgemarrow** [yishn/Sabaki#120]
Hi again,

For some reason, when I pulled and rebuilt today, some of the ui icons did not make it in the app (they are still in the repo). Any suggestion?

Thanks

![sabaki](https://cloud.githubusercontent.com/assets/9064665/17830678/9d19e070-670d-11e6-95ef-a04f34072336.png)

**Comment by yishn** [comment]
I can't do anything right now wince I'm on vacation. Can you try using an older version of Sasaki and see if this problem occurs? I'm guessing you use Linux?

**Comment by apetresc** [comment]
I can confirm this also happens on OSX:

![screenshot 2016-08-24 09 52 21](https://cloud.githubusercontent.com/assets/14872/17933023/781540aa-69e0-11e6-8463-6a2a876aed22.png)

**Comment by yishn** [comment]
I just got an idea: Can you try removing node_modules and installing them again? Octicons changed their folder structure in a major version update.

**Comment by georgemarrow** [comment]
Yep. That fixed it.
