### ISSUE TITLE
Huge performance difference with two nearly identical SGF files

### ISSUE THREAD

**Issue by FelixBrendel** [yishn/Sabaki#125]
Sabaki seems to perform a lot worse, when the SGF file contains **many separate games** in contrast to the **same amount of variations** of an empty board. Here is a [**zip containing two nearly identical "large" files**](https://github.com/yishn/Sabaki/files/457845/largeSGFs.zip). After opening **large1.sgf**, placing stones doesn't have any delay, with **large2.sgf** placing stones has a 1 second delay (at least on my machine). 

I don't know if this is a bug or maybe can be designed better (or maybe the design doesn't allow this).

**Comment by yishn** [comment]
Interesting... Running a CPU profile yields that the perpetrator is Sprint, a jQuery-like DOM manipulator. I think this is because of the sheer amount of HTML elements that are generated for each game inside the SGF collection.

**Comment by yishn** [comment]
This fixes the delay when placing stones. I'm keeping this issue open for the delay when opening the 'Manage Games...' dialog. Maybe we can try generating the SVG preview images on the fly (when scrolling)?
