### ISSUE TITLE
Unable to select correct move in guess mode

### ISSUE THREAD

**Issue by dsj9** [yishn/Sabaki#129]
When I toggle guess mode for any SGF file, I can narrow any move down the correct coordinate, but clicking that coordinate has no effect, and so I am unable to progress to the next move. I expected clicking the correct coordinate would continue on to the next move.

I am using Windows 10 and Sabaki v0.17.2 x64.

![2016-09-18](https://cloud.githubusercontent.com/assets/20363965/18612850/c9150a88-7d65-11e6-8fd1-733ed22ef3e8.jpg)

**Comment by yishn** [comment]
This issue is known and has been fixed in master. It will be corrected in the next release.
