### ISSUE TITLE
"Load From Clipboard" doesn't support UTF-8 encoding

### ISSUE THREAD

**Issue by aleadag** [yishn/Sabaki#133]
First, thanks for the great effort to make such an amazing Go editor tool.

In Mac OS X, if I copied a SGF, and loaded in Sabaki with "Load From Clipboard", the UTF-8 characters messed up.

**Comment by yishn** [comment]
I can't reproduce this issue. I tried copying the following text:

~~~
(;PB[古力]PW[柯洁]
;B[pd]
;W[dp]C[围棋 is fun])
~~~

Loading from clipboard works just fine in Sabaki.

**Comment by aleadag** [comment]
Mac OS 10.12
Sabaki: 1.18.0

Here goes the SGF file I copied to clipboard, and then load from Sabaki:

(;GM[1]FF[4]AP[Sabaki:0.18.0]CA[UTF-8]KM[6.5]SZ[19]AB[cd]C[如何挂角？]PL[W]
(;W[ec]
)(;W[ed]
)(;W[fd]
)(;W[fc]
))

Attached is the screenshot after I loaded.
![screen shot 2016-10-12 at 10 44 45 am 2](https://cloud.githubusercontent.com/assets/108791/19295701/f25c5d36-9068-11e6-8536-aa669d55a93f.png)

Please note the text in the comment area (right bottom corner).

**Comment by yishn** [comment]
Hmm... it seems like if I remove the `CA` property, it works fine. Which means this can be fixed if we ignore the encoding specified in `CA` when loading from clipboard.
