### ISSUE TITLE
Feature propose: Load Screen

### ISSUE THREAD

**Issue by Quanloh** [yishn/Sabaki#134]
The start-up of SABAKI appears to be slow on either Windows or MacOS,
It loads the board colour, background then the grid lines,
which makes it looked slow.
I think this is the nature of Electron.
Are we able to have a loading screen (SABAKI version, logo, creator info, etc) before the actual interface of SABAKI finished loading?
Or showing the interface only after all feature is loaded?

**Comment by yishn** [comment]
I don't think making a loading screen is possible with Electron. Showing the interface after everything has loaded is an option, but the amount of time one has to wait would be the same. It's a common trick to make things seem faster by showing a window as soon as possible, then load the interface.
