### ISSUE TITLE
Have support for running engines over ssh?

### ISSUE THREAD

**Issue by danielrich** [yishn/Sabaki#136]
Hey, 

This looks great! I do wish that it allowed for specifying gtp engines as a command rather than as a path. 

For example when I use gogui I run Leela on a different(beefy gpu) server. I can enter in 
"ssh daniel@myserver /home/daniel/exper/go/leela/leela070gtp_x64_opencl -g"
and that will work and allow me to play against leela on the other machine

With Sabaki though that gives me a connection error.

**Comment by yishn** [comment]
Can you try putting "ssh" as the path and "daniel@myserver /home/daniel/exper/go/leela/leela070gtp_x64_opencl -g" as arguments?

**Comment by danielrich** [comment]
ok now I feel silly. :) thanks! I should have explored that a little more thoroughly, sorry for the trouble. Now I really really like sabaki!
