### ISSUE TITLE
report on a Linux (Ubuntu) attempt to install Sabaki

### ISSUE THREAD

**Issue by pord17** [yishn/Sabaki#138]
On a recent and up-to-date Ubuntu:
$ sudo apt-get install nodejs
$ sudo apt-get install npm
$ npm run build:linux
This gives error messages about a missing "node"
$ sudo apt install nodejs-legacy
$ npm run build:linux
$ bin/sabaki-linux-x64/sabaki file.sgf

This yields a window with a dark dot where move 1 is going to be.
There are no navigation buttons. A navigation menu has "Forward --- Down arrow" but clicking the menu does not work, and there is no reaction to keys either. In fact no navigation seems possible. At the bottom right there is a button with three horizontal lines. Selecting the Info item shows players, date, event, so file.sgf was read successfully. In fact the player names are also given below the board.
No reaction at all is observed from choosing any of the menu items. (Left) clicking on the board gives alternatingly black and white stones. Middle and right clicks and keystrokes do not give any reaction. Since the menus do not work, saving is impossible. In short, this is mostly a failure. Leaving Sabaki elicits the question whether I want to save my changes. When I answer Yes, no filename is asked, but the input file is overwritten. My clicks have become a new variation in the given game.

$ npm test
...
Sabaki-master/test/boardTests.js:8
            let board = new Board()
            ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
...

Uninstalled everything again.

**Comment by yishn** [comment]
You don't have to build Sabaki in order to use it. I recommend downloading the prebuilt binaries from the [release page](https://github.com/yishn/Sabaki/releases). 

Of course, building Sabaki shouldn't have failed. I have some conjectures as to why it failed:

* Your node is not up to date. Run `node --version` to check your version. The tests are written in ES6 which is almost fully supported in node 6.9.0. 
* You haven't installed the dependencies by running `npm install`.
* Your npm is not up to date. Check your version with `npm -v` and run `sudo npm install npm -g` to update npm.

**Comment by pord17** [comment]
The software involved (sabaki, node,npm) was freshly installed. Now they have been removed again, but the versions must have been recent.

Using prebuilt binaries is a very dangerous thing to do. I really never do, but just this time I tried,
downloaded sabaki-v0.18.2-linux-x64.tar.gz, unpacked an ran the sabaki binary.
Comment on the unpack: unpacking littered the current directory. Standard is that foo-1.2.3.tar.gz unpacks to a subdirectory foo-1.2.3.
Comment on the execution: my window manager twm crashed, the system no longer reacted to mouse and keyboard. A reboot was needed. My first reboot in 2016. That is what happens if one runs random executables found somewhere on the net.

**Comment by yishn** [comment]
>  The software involved (sabaki, node,npm) was freshly installed [...] but the versions must have been recent.

Usually the node version you get with apt-get is an ancient one, like v0.6.19. Follow [these instructions](http://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version) to install the latest version v6.9.0. Same with npm.

> Comment on the unpack: unpacking littered the current directory. Standard is that foo-1.2.3.tar.gz unpacks to a subdirectory foo-1.2.3.

What standard are you speaking of?

> Comment on the execution: my window manager twm crashed, the system no longer reacted to mouse and keyboard.

Is it still on Ubuntu? If not, please state your Linux distribution and other data.

> That is what happens if one runs random executables found somewhere on the net.

These are not random executables, they are created by using the same method you are attempting to do.

**Comment by pord17** [comment]
Nothing wrong with the SGF (ASCII-only, no comments, small pro game). It was read correctly.
Sabaki is a random 69MB executable, full of libraries that were compiled on some system, with some version of the C library and dozens of other libraries. If my system was compiled with a different version of one of these libraries, crashes will happen. I expected a crash, but it was a bad crash, necessitating a reboot, since I lost mouse and keyboard.

It is bad to have a package unpack to a lot of junk in the current directory. Almost all packages, at least in a Linux environment, do the right thing, and unpack in a subdirectory. That makes it possible e.g. to have both foo-1.2.3 and foo-1.2.4. 

If one has a system like Ubuntu then doing things behind the back of their package manager only leads to trouble, and an instable system. If Sabaki really fails to work with the latest that Ubuntu provides, then I must wait a few years and come back if/when the node version needed by Sabaki is provided by Ubuntu.

By the way - I suppose you are aware of the node vs nodejs name variation?

**Comment by yishn** [comment]
> Sabaki is a random 69MB executable, full of libraries that were compiled on some system, with some version of the C library and dozens of other libraries. If my system was compiled with a different version of one of these libraries, crashes will happen.

Then you have to build [Electron](http://electron.atom.io/) by yourself as well since the run script downloads prebuilt binaries provided by Electron. I'm actually surprised that the binaries you got by running `npm run build:linux` didn't crash your system, too.

> If Sabaki really fails to work with the latest that Ubuntu provides [...]

Sabaki doesn't need node or npm to run; you only need them to build. 

> [...] then I must wait a few years and come back if/when the node version needed by Sabaki is provided by Ubuntu.

Ok, see you then! I'm closing this issue for now.
