### ISSUE TITLE
need help how to install on linux

### ISSUE THREAD

**Issue by mvkrdndm** [yishn/Sabaki#139]
it would be nice that beeing there a readme file explains how to install for linux .i use xubuntu , i see no .sh file , i have no idea how to install ,could someone tell me please.

**Comment by yishn** [comment]
It's very simple. Download the [latest release here](https://github.com/yishn/Sabaki/releases). Make sure to download the right architecture. Then unpack the archive. To run Sabaki, just run the executable `sabaki`.

**Comment by mvkrdndm** [comment]
ok.i knew it too .i was expecting maybe some installation steps like panda go ,it can run with executabe without installation but also you can install it by running install.sh file.if there is no installation ok
