### ISSUE TITLE
Allow both sides to be played by engines at once

### ISSUE THREAD

**Issue by 00dani** [yishn/Sabaki#140]
Currently if you assign an engine to one colour, the other colour will have its engine setting cleared. It should be possible to attach two engines (or two copies of the same engine) to the same Sabaki game and have them play against one another, rather than always requiring a human player.

**Comment by yishn** [comment]
This is going to be pretty difficult since I don't really know what to do with the GTP console. Also, I wonder how to redesign the "Attach" menu and deal with the "Generate Move" command. Which engine should Sasaki choose? There is also the question with how to stop the engines from playing if the user has had enough.

**Comment by 00dani** [comment]
Hmm. I guess it'd make the most sense to have *two* GTP consoles, one on each side of the screen, for the two possible attached engines - perhaps using inverted colour schemes, so the white player has a light console background? Sabaki would need to bridge GTP messages between the two engines, such that a `genmove` result from one side becomes a `play` on the other side - GTP was designed to support this exact situation though, so that shouldn't be an issue.

As for the menus, I started writing a suggestion for replacing the Attach submenu with two submenus (one for each colour), but then realised that duplicating the *entire* Engine menu may work better - perhaps as menus called Black and White, or "Black Engine" and "White Engine" if that seems clearer. Then you've got somewhere to put separate toggle/clear console options for each side too.

Incidentally I don't think Attach really needs to be a submenu at all - the engine menu/menus could simply list the available engines inline. In other words, you'd have two adjacent menus which look like this:
![screen shot 2016-11-03 at 10 34 34](https://cloud.githubusercontent.com/assets/610876/19951297/300939fc-a1b1-11e6-97ee-cdd9fec2312f.png)

So that the user can stop the engines from playing, you'd want to provide a short delay between each move. Perhaps show a small shrinking progress bar to indicate "time until next move", next to a button for cancelling the countdown and interrupting play.

Yeah, it involves quite a few changes, but having engines compete is a fairly important part of the Go scene - as evidenced by GTP explicitly supporting that setup - and should be available in Sabaki.
