### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by y-ich** [yishn/Sabaki#144]
Hi, thank you for providing your nice app!

Do you have any plan for i18n?
If you determine a framework, I will gladly cooperate for Japanese^^

**Comment by yishn** [comment]
I18n is nice, but I don't think Sabaki is ready yet, or ready in the near future. But if I do get it ready, I'll be sure to let you know. 😄

**Comment by aniljava** [comment]
I can pitch in, but i need some help and okay from @yishn .

I have not coded properly in node.js or electron but have moderate experience with js in general. Here is an outline of the proposal:

1. new module `i18n.js` in modules that has language loader and helper function.
2. new directory `locales` inside modules containing 'en.js' and other locales jp.js, es.js ... .
3. add key to settings.js for language override. By default the `app.getLocale()` is used. If there is a `locale` option in settings, it is used instead.
4. Edit in preferences panel to include language option.
5. Go over all files (js, html) and find the strings and replace with `i18n.translate("String used there")`.

Let me know.

**Comment by yishn** [comment]
I'm sorry, but I'm not ready to add i18n just yet... Maybe when Sabaki reaches version 1.0. I'm closing this issue for now. I'll reopen when Sabaki is ready.
