### ISSUE TITLE
Bug: Pressing "Cancel" still closes the apps

### ISSUE THREAD

**Issue by Quanloh** [yishn/Sabaki#149]
Hi @yishn ,

When I was editing a variation,
I accidentally clicked on the exit "X".
Sabaki asked if I want to save and exit,
I clicked "Cancel", but it still exited.

I manage to reproduce this,
as long as i added something in the variation branch.

tested on Windows 7 64 bit.

Regards,
QuanLoh

**Comment by Quanloh** [comment]
Hi @yishn ,

I found something else.

Record a game,
click the exit "X" to exit Sabaki,
select "Save" when asked,
click "Cancel" when asked for file name and location,
then Sabaki exits.

Regards,
QuanLoh

**Comment by yishn** [comment]
Hm... it seems like the first one is an Electron bug electron/electron#7977.
