### ISSUE TITLE
Get the score from the engine

### ISSUE THREAD

**Issue by Zenigata** [yishn/Sabaki#152]
When playing against an engine, can you use its response to estimate the score when the game is over? The best is to instantly give the score when the game is over and thus to not wait for the player's input.

**Comment by yishn** [comment]
Can you clarify? What do you mean by "game is over"? Sabaki will automatically enter scoring mode if there are two consecutive passes. Also, when the engine resigns, it doesn't make sense to score the game.

**Comment by Zenigata** [comment]
Damn, you're right. I was willing to test the scoring mode when the engine suddenly resigned... Nevertheless I want to get the final results without the player's input. Maybe I will code it in a fork. I will certainly close this issue.
