### ISSUE TITLE
2.mp3 not found

### ISSUE THREAD

**Issue by Zenigata** [yishn/Sabaki#153]
When playing this error suddenly popped 20 times in the console : file:///.../Sabaki/bin/sabaki-win32-x64/resources/app.asar/sound/2.mp3 net::ERR_REQUEST_RANGE_NOT_SATISFIABLE. Any idea?
PS: I had a 0.mp3 not found too.

**Comment by Zenigata** [comment]
By the way I don't know what is Autoplay mode and how to use it. Can you explain it to me? Thx.

**Comment by yishn** [comment]
I have no idea, I can't reproduce the issue. Did you maybe accidentally deleted the `sound` folder? You can try unpacking `app.asar` and see if you can find the file `sound/2.mp3`.

**Comment by Zenigata** [comment]
How do you unpack it? Using 7z doesn't seem to work. I had these errors when playing against the latest version of pachi, randomly so it seems.

**Comment by yishn** [comment]
You can unpack them using [asar](https://github.com/electron/asar).

**Comment by yishn** [comment]
I assume this has been fixed.
