### ISSUE TITLE
Feature Request : Pinned Edit Mode

### ISSUE THREAD

**Issue by aniljava** [yishn/Sabaki#155]
Instead of <B/W> switch and menu bar, merge or have a switch to merge with Edit/Annotation. Allowing one click annotation when required. The current two step process is kind of hassle.

Use separate stones for current B/W stone in edit mode. And use merged stone as an icon to get out of the edit mode.

**Comment by yishn** [comment]
I'm sorry, but I don't understand at all what you're saying... What's the <B/W> switch? What do you mean by 'to merge with Edit/Annotation'? How do you propose one click annotations? What do you mean by 'use merged stone as an icon to get out of the edit mode'?

**Comment by aniljava** [comment]
<B/W> Switch is the button between Black and White at the bottom center. It alternates between black and white during the game play and when you take mouse over it, it says "black to play" or "white to play".

When the game is in edit mode, the bottom bar is replaced with new bar containing cross, triangles, squares .... Here too the first icon that alternates between black top or white top depending on which color stone you want to add. I am talking about that first icon as <B/W> icon. The tool tip says "stone tool" . 

Currently app allows either play mode (default mode) in which the color of stone alternates after each play. If i need to put some markers like triangles i need to click on menu icon at bottom left and choose edit. After which Black <B/W> White bar is replaced with new bar with triangle, squares .. bar. I need to pick a marker from those and click on positions to mark those positions with those markers. Once done i need to close the bar with cross icon at bottom right. After that the game is back to play mode with alternating black and white. 

My understanding is once you are in edit mode, only way to get back to alternating black and white stone is by closing the edit mode. 

My proposal was to allow game to progress while the edit bar is visible at the bottom. To make the game to progress to next move and get back alternating black without closing the edit bar at bottom i am proposing a new icon that says, colors will be changed after each click.

We can have new icon that can be clicked instead of close icon at left to say that the game is in play or alternating color mode. I thought <B/W> icon used as the first icon on edit bar for this. And add two new icons to represent black and white stone placement.

**Comment by yishn** [comment]
Thank you for the clarification. While it's an interesting idea, I think what you're proposing goes against the philosophy of the edit mode. In edit mode, you only change the current node without progressing the game. Allowing the user to play in edit mode is just confusing and defies its purpose.

That said, you can still *navigate* in edit mode by scrolling the mouse wheel or using the game tree and move slider. 

If you want to place black and white stones alternatively (without progressing the game) you can equip the stone tool in edit mode and right click on the board. This will place a stone with the secondary color on the board.

If you have comments opened in the sidebar, clicking on the pencil will enter edit mode as well. There are keyboard shortcuts for entering/leaving edit mode (`Ctrl/Cmd+E` or `Ctrl/Cmd+[1-8]` and `Esc`).
