### ISSUE TITLE
Margin around goban

### ISSUE THREAD

**Issue by aniljava** [yishn/Sabaki#156]
I tried tinkering around the css to have an uniform space around overall goban. I think the sizes updated dynamically from js on resize. What is the easiest way to introduce this margin. Would like to avoid the tinkering with js, but wont mind if needed.

thanks

**Comment by yishn** [comment]
You're right, the sizes are updated dynamically. I can rewrite the resizing logic that it takes the `padding` of `#main` into account.

**Comment by yishn** [comment]
With this, you only need to add

~~~css
#main { padding: 10px }
~~~

to your userstyle to introduce a margin of `10px` in the next version of Sabaki.
