### ISSUE TITLE
Generate a .desktop file for Linux builds

### ISSUE THREAD

**Issue by apetresc** [yishn/Sabaki#158]
Most Linux desktops can only associate file extensions with [.desktop files](https://wiki.archlinux.org/index.php/Desktop_entries), not random binaries. So, without one, you can't associate Sabaki with SGFs. Creating one yourself isn't a big deal, but a lot of applications will just generate one for you (and `make install` will put it into `/usr/share/applications` but I guess Sabaki isn't supposed to have an install script). So it might be nice if this was part of the `npm run build:linux` flow.

**Comment by apetresc** [comment]
Hmm, I was trying to implement this one myself, but I can't seem to find the `electron-builder` configuration at all, only the `electron-packager`. Is the `electron-builder` configuration not committed to the repository to protect the signing keys, etc, or do you just not use it at all?

**Comment by yishn** [comment]
Currently, I only use electron-packager. Is there a reason you need electron-builder?

**Comment by apetresc** [comment]
Oh, no, I just assumed you were using `electron-builder` since the Mac/Windows builds prompt to auto-update, which I thought was an `electron-builder`-only feature.

In that case, I'm not sure if `electron-packager` even knows how to generated `.desktop` files by itself, might have to just manually render a template =/

**Comment by yishn** [comment]
Haha... sadly, it's not a prompt to auto-update, it's a prompt to manually update. I just check the GitHub releases page if the version is up to date. 😆 It works under Linux as well.

**Comment by apetresc** [comment]
Ah, okay :) I just build from source, so I never used the auto-update, I
assumed it actually ran it!

So, in that case, maybe I can rephrase this ticket as - generate
installers/packages for each platform using `electron-builder`. Seems like
it will have even more utility than just Linux desktop integration. It's
also something I can try to tackle, if you'd like.

What do you think?

**Comment by yishn** [comment]
I've looked into `electron-builder`, it seems to have a lot of options... If you want to tackle it, then I'll give my OK. 👍
