### ISSUE TITLE
Copying to and loading from clipboard for web build

### ISSUE THREAD

**Issue by C0DEHERO** [yishn/Sabaki#160]
The web build doesn't seem to support copying the sgf to the clipboard or loading an sgf from the clipboard, even though that would be very convenient feature for the web version. Since the desktop build already has that feature, it probably shouldn't be too hard to add it to the web build.

**Comment by yishn** [comment]
Copying things to the clipboard is not a problem nowadays, but AFAIK the browser can't read the clipboard.

**Comment by C0DEHERO** [comment]
Well no, but you could pop up a text box to paste the sgf inside, sort of like the gokibitz text upload box.

**Comment by yishn** [comment]
Yeah, I just wanted to point out that the implication "desktop build already has that feature ⟹ it shouldn't be too hard" is not correct. 😃

**Comment by C0DEHERO** [comment]
Oh, true I guess :D I just figured you wouldn't have to write much extra code since the desktop and web build use the same code base, but then I don't know anything about javascript or electron.
