### ISSUE TITLE
Warn when overwriting SGF files

### ISSUE THREAD

**Issue by jshholland** [yishn/Sabaki#162]
I tried to save an SGF of a tsumego with the same name as an already existing file, and it just silently overwrote the file. It would be better to show a warning and allow manual confirmation if this happens.

Running on Linux with a GTK-looking file chooser, not tested on other platforms.

**Comment by yishn** [comment]
Sorry, I don't know what you mean. Can you post step by step instructions how to reproduce this, what happens, and what you expect Sabaki to do?

**Comment by jshholland** [comment]
What I do:
1. create and edit a new file
2. save it as test.sgf
3. open another new file and edit it to something else
4. save it with the same name (test.sgf)
What I expect:
A warning saying "File with this name already exists. Overwrite, y/n?"
What happens instead:
The first file is overwritten silently.

**Comment by yishn** [comment]
Hm... I can't reproduce this in Ubuntu. I get a native confirmation dialog as one would expect:

![screenshot from 2017-01-26 23-33-01](https://cloud.githubusercontent.com/assets/9217349/22353333/366d9796-e420-11e6-9996-8bc3fd9211aa.png)

This is stuff that Electron should handle and Electron uses native APIs to show the dialogs. This feature should be provided by the operating system. There's nothing I can do.
