### ISSUE TITLE
"Horizontal mode" for game tree, keyboard shortcuts

### ISSUE THREAD

**Issue by apetresc** [yishn/Sabaki#166]
Having spent over a decade with SGF editors such as CGoban, PandaGo, etc. before Sabaki existed, I have a very engrained muscle memory for traversing an SGF tree "horizontally"; that is, lines move from left to right, and variations branch up/down.

One of the only frustrating things about using Sabaki for me is that I have to flip my mental model 90°, using up/down to go down a line and left/right to switch branches. I often accidentally revert to the old way, and lose my place in the tree.

I would love to be able to toggle (perhaps in the config JSON) between horizontal mode and vertical mode. The main changes would be:
1. Rotate the tree viewer 90°
2. Potentially move it from the vertical top-right pane to a horizontal pane below the board, so that you can see more of it at once in this alignment
3. Remap all the relevant keyboard shortcuts to ones that make sense horizontally

I have [a branch on my fork](https://github.com/apetresc/Sabaki/tree/horizontal-tree) where I started doing this. So far I've only solved 1. on the list above; I couldn't figure out how to remap shortcut keys dynamically in Electron, so I gave up. But maybe @yishn has some ideas on how/if to accomplish it. It doesn't technically _need_ to be dynamic, we could easily just require a restart to switch modes.

**Comment by yishn** [comment]
Switching between a horizontal and vertical tree requires to add a complexity to Sabaki (particularly point 2 and 3, also some menu item labels need to be changed, the slider should change orientation too) which I don't want to trade for the mere addition of a horizontal tree. However, feel free to add this functionality in your own fork, Sabaki is open source after all. I'm closing this issue, but if you have any questions, don't hesitate to ask.

As for how to remap shortcut keys dynamically, the easiest way is to rebuild the menu by calling

~~~js
ipcRenderer.send('build-menu')
~~~

in the renderer process. This will invoke the function `buildMenu()` in `main.js` which will take `menu.json` and turn it into an actual menu. I would add some appropriate logic in there that determines which keyboard shortcut to use depending on which orientation the tree has.
