### ISSUE TITLE
Mac OS app terminates when opening .sgf file

### ISSUE THREAD

**Issue by jylim2016** [yishn/Sabaki#169]
I built the Mac OS app from source without issues. App loads and plays games without problem but when I tried to open an sgf file, the app terminates unexpectedly. Also tried saving games in-app and encountered the same issue when re-opening them.

Is there a dependency that I may have missed out?

Thanks!

**Comment by yishn** [comment]
That is weird... Can you try [opening the developer tools](https://github.com/yishn/Sabaki/wiki/Debugging) and see if the console shows any errors? Also, does the prebuilt binary exhibit this behaviour?

**Comment by yishn** [comment]
Apparently, the new macOS icon of Sabaki is causing this.

**Comment by jylim2016** [comment]
Thanks very much for looking into this! Starred for the great app and support 👍
