### ISSUE TITLE
Build instructions out of date (wiki)

### ISSUE THREAD

**Issue by mkaemmerer** [yishn/Sabaki#170]
The current wiki page says that Sabaki can be built using these commands:

```
$ npm run pack
$ npm run dist
$ npm run dist:win
```

All of these commands error out. `npm ERR! missing script: pack`.

The correct way to build Sabaki seems to be the command
```
$npm run build:win
```

**Comment by mkaemmerer** [comment]
Updated the wiki with revision: https://github.com/yishn/Sabaki/wiki/Building-&-Tests/408699d9004bff8df1f25c6e1b74d05044e940ea.

Let me know if I made any mistakes.

**Comment by yishn** [comment]
Yes, you made a mistake, the `build:{os}` commands are the old ones. If you pull the most recent master branch, you'll see that the commands have been changed.

**Comment by mkaemmerer** [comment]
Oh I see! Thanks for the clarification.

I was attempting to build the source code from here, which must be from earlier: https://github.com/yishn/Sabaki/releases/tag/v0.20.0

**Comment by yishn** [comment]
Yes, the change was made only recently (read: just now 😆). Unfortunately the wiki on GitHub is quite limited. It can only hold the most recent information and is not tied to any commits in the main project... Maybe I should put the instructions in the readme file instead.
