### ISSUE TITLE
Right arrow behavior is confusing, possibly buggy

### ISSUE THREAD

**Issue by dfannius** [yishn/Sabaki#174]
Sometimes when I press the right arrow I get taken to a child node rather than a sibling node, which is not the expected behavior for me. To reproduce, load the SGF file https://gist.github.com/dfannius/583648a0bea836c13aef5ca2a61b80e0, press down-arrow twice, and then right-arrow once.

I don't understand the code well enough to fix it, but it seems that `sabaki.goToSiblingVariation` is being too aggressive in setting `navigate`, which decides whether we are considering children or siblings of the current node. It's not obvious to me why we'd ever want the `navigate=true` behavior, so I may be misunderstanding the intent.

**Comment by yishn** [comment]
Yeah, I guess you're right about this behavior being unexpected. My original thought was: If a node has a horizontal line in the game tree, then pressing right should follow the line to the corresponding variation.
