### ISSUE TITLE
Goban grid lines are much blurrier in 20.1

### ISSUE THREAD

**Issue by fohristiwhirl** [yishn/Sabaki#175]
http://i.imgur.com/JxHh6nW.png

On the left is 20.0, on the right is 20.1.

The lines on the left are much crisper and sharper.

Although this is the default theme, things are also like this on my own theme. Did something change in how lines are drawn?

**Comment by yishn** [comment]
No, the line "drawing" didn't change, but I did upgrade Electron to v1.6.1, which comes with an upgraded Chrome version, which might be responsible for this... 

I'm noticing that the bottom bar in v0.20.1 is bigger than in v0.20.0, which might indicate that the zoom level of the web page has changed. Your Windows uses a much bigger font size than usual. It might be the case that Electron v1.6.1 is adjusting the zoom level depending on your system settings, but I don't really know...

**Comment by fohristiwhirl** [comment]
That'll be it, I'm sure. I have everything at 125% size in the Display control panel.

**Comment by yishn** [comment]
Maybe it's a good idea to replace all grid line images with vector images. It won't fix the wood texture being blurry, though.

**Comment by fohristiwhirl** [comment]
Uh, I wonder how much trouble it would be to add some sort of workaround as an option in the settings.json, where I could ask for 0.8 size to counteract it, and then the code would do something like:

let contents = win.webContents;
contents.setZoomFactor(0.8);         // Or whatever is set...

**Comment by yishn** [comment]
That would be very quick and hacky; I can add a settings key for that. :grinning:

**Comment by yishn** [comment]
It's done, and the key's name is `debug.zoom_factor`. I'll keep this issue open for the vector images of the grid lines.

**Comment by fohristiwhirl** [comment]
Thanks, good to have.

**Comment by fohristiwhirl** [comment]
Although the bad news is that the saved window size now doesn't really work.

**Comment by yishn** [comment]
Can you elaborate on that?

**Comment by fohristiwhirl** [comment]
When I set to 0.8, the window gets bigger every time I open the app.

**Comment by yishn** [comment]
I've hopefully added a fix for that, can you try it?

**Comment by fohristiwhirl** [comment]
Yes I think that's working now.

**Comment by fohristiwhirl** [comment]
It's a minor thing, but (with a setting of 0.8) the menu in the bottom right (Pass, Resign, Edit, etc) is placed too far right and down.

**Comment by yishn** [comment]
I guess everything that measures the DOM for menu placement is bound to have some errors. I don't think this can be fixed... Unless we open the menu at the current mouse position instead.

**Comment by fohristiwhirl** [comment]
Making it

        Math.round($('#headermenu').offset().left * setting.get('debug.zoom_factor')),
        Math.round($('header').offset().top * setting.get('debug.zoom_factor'))

I think works. Although I don't know how many places in the code would need to be littered with this stuff.
