### ISSUE TITLE
Windows installer bug

### ISSUE THREAD

**Issue by ParmuzinAlexander** [yishn/Sabaki#176]
Windows installer remove all files in target folder, example GTP engine and SGF files.

**Comment by yishn** [comment]
I'm not sure if this is a bug. When installing a newer version, we do want to uninstall the previous version of Sabaki first. Personal files shouldn't be in the software installation directory in the first place.

**Comment by fohristiwhirl** [comment]
I'm experimenting and things seem quite inconsistent, it doesn't always happen...

However, this is dangerous. Someone might try to install to their Desktop, for instance, by simply selecting their desktop. Actually I did this the other day, and it seemed to hang - presumably it was actually trying to delete my files, though I aborted and I don't think anything too important is missing.

**Comment by yishn** [comment]
I agree it's dangerous. Looks like someone already filed an issue at electron-userland/electron-builder#1298. There's also a PR for it, but it's not merged yet. I can also disallow people from choosing the installation directory altogether.

**Comment by ParmuzinAlexander** [comment]
Update needs overwrite files not delete all! User can store here any files. Uninstall Sabaki.exe remove all files and other Sabaki install without questions and warnings! What happens if mistake install to root Program Files and Uninstall? Root C:\?

**Comment by yishn** [comment]
I'm going to merge this into #186. Subscribe there for updates.
