### ISSUE TITLE
cannot install under mac os x "requires a peer of ajv@>=5.0.3-beta.0 but none was installed."

### ISSUE THREAD

**Issue by kwccoin** [yishn/Sabaki#179]
Strange if one ignore it, whilst one cannot generate the mac version, one can still generate a web version and run on a browser.  

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@^1.0.3 (node_modules/7zip-bin/node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.0.3: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^2.0.2 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.0.2: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN ajv-keywords@2.0.1-beta.1 requires a peer of ajv@>=5.0.3-beta.0 but none was installed.

**Comment by yishn** [comment]
Seems like this has something to do with electron-userland/electron-builder#1344. This is only a warning though, does `npm run pack` and `npm run dist:macos` work?

**Comment by dfannius** [comment]
I got past this by following the directions at [https://github.com/epoberezkin/ajv](https://github.com/epoberezkin/ajv) which say to run `npm install ajv@^5.0.3-beta`.

**Comment by yishn** [comment]
This is only a warning and does not affect building. I'm closing this, as it can't be fixed.
