### ISSUE TITLE
Should allow moves to overwrite previous contents.

### ISSUE THREAD

**Issue by fohristiwhirl** [yishn/Sabaki#182]
(This is a tiny issue but also easy to fix, I think.)

According to red-bean... http://www.red-bean.com/sgf/go.html

`When a B (resp. W) property is encountered, a stone of that color is placed on the given position (no matter what was there before).`

Currently Sabaki ignores moves that overwrite a stone that is already there. I believe this can be fixed to match the recommended behaviour with 2 tiny changes:

* Commenting out line 382 in board.js (which checks for a stone already present).
* Changing the word `this` on line 395 to be `move` instead (so that the new board is used to determine which chains to remove, if capturing).

This test file works after both these changes are made:

```
(;GM[1]FF[4]CA[UTF-8]SZ[19]
;B[jg];W[kh];B[jh];W[ki];B[ji];W[jj];B[kg];W[lg];B[jf];W[kf]
;B[je];W[ke];B[cn];W[jd];B[ci];W[ie];B[cf];W[if];B[ck];W[ig]
;B[en];W[jg])
```

**Comment by yishn** [comment]
Nice catch! I have overlooked that detail of the SGF specification. If you like, you can submit a PR and add a test case for this.

**Comment by fohristiwhirl** [comment]
OK, I will.
