### ISSUE TITLE
Initial board saves its size like SZ[19:19]

### ISSUE THREAD

**Issue by fohristiwhirl** [yishn/Sabaki#185]
If you open Sabaki, maybe play a few moves, and save, the file will have its size saved in the long format, e.g. SZ[19:19]. This doesn't happen if you ever select "New".

For compatibility with older SGF editors, it would be better not to save the long format where possible.

Update: I think I can fix this actually... it's very minor changes to sabaki.getEmptyGameTree:

    let sizeProperty = size[0] + (size.length > 1 ? ':' + size.slice(-1)[0] : '')

And then use that inside the template...

    `SZ[${sizeProperty}]`,

If you agree, I can make a pull request if you wish, but it's a simple enough change we could avoid it...

**Comment by yishn** [comment]
Yeah, I came across this during my preact rewrite and fixed it there already.
