### ISSUE TITLE
Windows (un)installer deletes all sibling files where it is run!

### ISSUE THREAD

**Issue by TheIronMarx** [yishn/Sabaki#186]
Possibly related to #176 .

When installing, I assumed it would create a folder for itself and I selected a Program Files folder on a disk containing a lot of important metadata for software. It did not. I assumed I could safely use the uninstaller to clear out those new files. And the thing just starts expelling everything in the folder.

For God's sake that can't be the functionality of an uninstaller! If it's an Electron issue, scrap the uninstaller with the release.

**Comment by yishn** [comment]
I'm so sorry, I hope nothing really important got deleted! I guess I'm just going back to plain old 7z file after these fiascos with the Windows installer. At least until electron-builder gets its shit together.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/pull/1301 will be merged soon.

> guess I'm just going back to plain old 7z archive after these fiascos with the Windows installer.

You can use `portable` target to create portable windows app without installation.

**Comment by yishn** [comment]
@develar Thank you for your work! I'll try out the portable target.

**Comment by yishn** [comment]
@develar The `portable` target looks good in theory, but there are a few caveats I can't live with:

1. It takes longer time to start the portable version than the non-portable version.
2. Arguments aren't passed to electron which makes it unusable as an editor. (E.g. opening files in Windows Explorer by clicking 'Open With...' and selecting the portable version won't open the file.)

Also another reason I'm using the installer is the automatic file association that comes with it.

**Comment by develar** [comment]
I will merge https://github.com/electron-userland/electron-builder/pull/1301 tomorrow.

 > It takes longer time to start the portable version than the non-portable version.

zip compression maybe used, I will check.

> Arguments aren't passed to electron which makes it unusable as an editor

it is bug, I will check it (could you please file issue?)

> Also another reason I'm using the installer is the automatic file association that comes with it.

Yes. And auto-update.

**Comment by yishn** [comment]
I've opened an issue at electron-userland/electron-builder#1410.

**Comment by develar** [comment]
Error fixed in the electron-builder 16.5.0

**Comment by TheIronMarx** [comment]
Thank you for dealing with this so swiftly.
