### ISSUE TITLE
No big icons on Windows

### ISSUE THREAD

**Issue by ParmuzinAlexander** [yishn/Sabaki#187]
It minor but no big icons Sabaki.exe

**Comment by yishn** [comment]
I have no idea what causes this... Inspecting the executable file with Resource Hacker yields that everything's fine. And if I copy the executable file to another location, Windows Explorer shows the icon correctly. Clearing icon cache doesn't seem to help...

**Comment by ParmuzinAlexander** [comment]
Yes, only C:\Program Files\Sabaki and x64 version not show... Very strange.
