### ISSUE TITLE
Automatically detect character encoding in SGF

### ISSUE THREAD

**Issue by shuodaowang** [yishn/Sabaki#188]
the mac version I am using now doesn't display GBK Chinese characters correctly.  quite some sgf files have very nice comments in Chinese.  please help!

**Comment by yishn** [comment]
Make sure your sgf files have a correct CA property, see https://github.com/yishn/Sabaki/issues/121#issuecomment-246104194.

**Comment by fohristiwhirl** [comment]
In theory, missing CA means ISO-8859-1 but in practice this often isn't true. One might consider using jschardet if CA isn't present. I could make a go at writing this, if you wanted.

**Comment by yishn** [comment]
@fohristiwhirl Okay, we can give it a try. @shuodaowang Can you provide the SGF file you have issues with, so we can test on it?
