### ISSUE TITLE
Smaller coordinate numbers

### ISSUE THREAD

**Issue by Thegoban** [yishn/Sabaki#190]
I very much like distractless playing... I´d like my Sabaki look like the screenshots in the web page, I want to be so civilized!, how is it done :).

Ah, and the numbers... can´t they be civilizedly smaller please?

Great project, thank you!

**Comment by yishn** [comment]
Hiding the menu bar is not possible. On macOS the menu bar is outside the window, that's why there's no menu bar in the screenshots. You can try fullscreen (View > Toggle Full Screen) for distractless playing.
