### ISSUE TITLE
Java an Python gtp engines not attaching.

### ISSUE THREAD

**Issue by Thegoban** [yishn/Sabaki#191]
I have a collection of gtp engines working in Gogui, mostly all of them attach to Sabaki, but I´m getting mad to attach those written in java or python:

Engines working:
-----------------

Fuego 1.1
C:\Program Files (x86)\Fuego\fuego.exe

Pachi UCT 11.00 (Retsugen)
C:\Users\me\Go_engines\pachi-11.00-win32\pachi.exe

Michi-c (simple go program demo) 
C:\Users\me\Go_engines\michi-c-master\michi.exe gtp

Oakfoam  0.1.3
C:\Program Files (x86)\Oakfoam\oakfoam.exe

GnuGo 3.8
C:\Users\me\Go_engines\gnugo-3.8\gnugo-3.8\gnugo.exe --mode gtp

Mogo release 1
C:\Users\me\Go_engines\MoGo_release3\mogo.exe

Aya 6.34
C:\Users\me\Go_engines\aya634e\Aya.exe --mode gtp

Leela 0.9.0
C:\Users\me\Go_engines\Leela090GTP\Leela090GTP.exe --gtp

GoTraxx 1.4.2.(beta)
C:\Program Files (x86)\GoTraxx\GoTraxx.exe

Go169 0.1
C:\Users\me\Go_engines\Go169\Go169.exe

Amigo 1.8
C:\Program Files (x86)\AmiGo\amigogtp.exe

Brown 1.0
C:\Users\me\Go_engines\brown-1.0\brown.exe

RandomGo 0.0
C:\Users\me\Go_engines\randomGo\randomGo.exe

Engines not attaching:
----------------------

Michi simple go program demo(Python)
C:\python27\python.exe C:\Users\me\Go_engines\michi-master\michi.py gtp

Disco (unknown version)
C:/python27/python C:\Users\me\Go_engines\disco-0.3\disco.py

Orego 8
Command:             java -ea -Xmx1024M edu.lclark.orego.ui.Orego
working directory: C:\Users\me\Downloads\orego\

Stop 0.9-005
Command:              java -jar stop-0.9-005.jar --mode gtp
Working directory: C:\Users\me\Go_engines\stop\

Ergo 1.0(bash)
C:\Users\me\bash.bat

Ergo is a special case, I can´t build it to work in windows with Mingw, so I run the Linux binary
in bash (windows subsystem for Linux), I can run it invoking bash in cmd, but can´t figure out how to attach it to Gogui or Sabaki... never mind

That were the "commands" I pass to Gogui to start each program, any idea about how to attach Java and Python engines to Sabaki??

PS: some of them won´t work w/o double quotes in gogui! I have removed them for Sabaki.

**Comment by yishn** [comment]
Can you show me the entries of the non-working engines as how they are in Sabaki? (Just take a screenshot) It's possible you have path and arguments wrong. Make sure to separate path and arguments, and make sure to put arguments in double quotes when necessary.

**Comment by fohristiwhirl** [comment]
Actually I can confirm using a .bat file works on Windows.

**Comment by yishn** [comment]
After reading the documentation of node.js again, I can confirm that you're right, @fohristiwhirl.

**Comment by fohristiwhirl** [comment]
I was able to get Disco running. (This particular program dislikes non-9x9 boards though.)

Simply use the path to python as the path and the path to the script as the argument, i.e. it should look like this:

http://i.imgur.com/nTThveI.png

**Comment by Thegoban** [comment]
Great idea!, I have 4 batchs whith all programs (except for ergo) running, but your idea is much more cleaner... pasing paths as options... lets try

thank you.

my .bat looks like this for each Python engines

C:\python27\python.exe  C:\Users\mateo_7otms94\Go_engines\michi-master\michi.py gtp
C:/python27/python C:\Users\mateo_7otms94\Go_engines\disco-0.3\disco.py


And like this for the Java ones:

cd C:\Users\mateo_7otms94\Go_engines\stop\ & java -jar stop-0.9-005.jar --mode gtp

cd C:\Users\mateo_7otms94\Downloads\orego\ & java -ea -Xmx1024M edu.lclark.orego.ui.Orego

**Comment by Thegoban** [comment]
Finally I´m more confortable with *.bat files.
Now Ergo (wich is a linux binary) is the only that refuses to attach.
I can launch it in cmd... like this 

[ cd C:\Users\me\Go_engines\ergo-master\ & bash -c /mnt/c/Users/mateo_7otms94/Go_engines/ergo-master/'ergo -g']

look here:
![ergo2](https://cloud.githubusercontent.com/assets/26829484/24589481/53d4b370-17db-11e7-9499-7d18ffbf0ccb.PNG)

I can launch it by double clicking in the batch file or by directly typing it in cmd...
I think that should work in Sabaki too, if I can use the keyboard, why Sabaki can´t speak to it?

**Comment by yishn** [comment]
If I may ask for future reference, what did you do to make your non-working bat files work?

**Comment by Thegoban** [comment]
Some reference ;)

Working in both, Linux and Windows:

Amigo,Aya, Brown, Disco, fuego, Gnugo, Go169, Leela, Mogo, Oakfoam, Orego, Pachi, Stop, Michi (Python), Michi (c), **Michic2.

Amigo: (no arguments)
 
Aya --mode gtp:
Runs great with Wine in Linux.

#!/bin/sh
cd ~/go_engines/aya634e/ && wine Aya.exe --mode gtp

Brown (no arguments):
 
Disco (no arguments):
  In Linux I start it with one .sh

#!/bin/sh
python ~/go_engines/disco-0.3/disco.py

In Windows with a .bat

@echo off
C:\python27\python C:%HomePath%\Go_engines\disco-0.3\disco.py

Fuego (no arguments)
Gnugo --mode gtp

Go169 (no arguments):
      
#!/bin/sh
cd ~/go_engines/go169/ && wine Go169.exe

Leela (-g, --gtp)
Mogo (no arguments)
Oakfoam (no arguments)

Orego (no arguments):

#!/bin/sh
cd ~/go_engines/orego/Orego-master/src && java -ea -Xmx1024M edu.lclark.orego.ui.Orego   

@echo off
cd C:%HomePath%\Downloads\orego\ & java -ea -Xmx1024M edu.lclark.orego.ui.Orego

Pachi (no arguments)

Michi gtp (Python):
#!/bin/sh
python ~/go_engines/michi-master/michi.py gtp

@echo off
C:\python27\python.exe C:%HomePath%\Go_engines\michi-master\michi.py gtp

Working in Linux:

Ergo -g, Hara (no arguments), indigo -gtp,  MarcosGo (no arguments) 

Working in Windows:

Gotraxx (no arguments)


 * Some programs marked as "no arguments" may accept "arguments", but they are not necesary to run it in gtp mode.
 
** Michic2 is buggy in windows, maybe my fault compilling it.

**Comment by Thegoban** [comment]
What is IMPOSSIBLE is running a linux program in windows (bash over wsl) and make it comunicate with Sabaki, it seems that microsoft politics is "What happens in bash, stays in bash"

@echo off
cd C:%HomePath%\Go_engines\ergo-master\ & bash -c './ergo -g'

will work double clicking on it or typing in cmd, but if you enable "legacy terminal" in cmd properties... it stops working, I´m not a developer... but can make an idea... I supouse that it´ll be hard or impossible to implement a console that can comunicate with bash untill Microsoft thinks it is apropiate.

**Comment by yishn** [comment]
Thank you for the information!
