### ISSUE TITLE
Smaller hoshi dots?

### ISSUE THREAD

**Issue by Thegoban** [yishn/Sabaki#192]
I´m theming Sabaki, I´ve tried to read the documentation but there is few information about stilling,
Is there a way of making hoshis smaller? I really need it.

**Comment by yishn** [comment]
If you want the hoshis to be `x` big, use the following:

~~~css
.goban .row li.hoshi::after {
    width: ${x};
    height: ${x};
    margin-top: calc(${x / 2} - 1px);
    margin-left: calc(${x / 2} - 1px);
    border-radius: ${x};
}
~~~

**Comment by Thegoban** [comment]
Thank you very MUCH!

**Comment by Thegoban** [comment]
Sorry to say I´ve been unable to do anything with the above code, fortunately and SURPRISINGLY I have been able to tweek the below CSS that was found between the sources that did quite well the trick.

 .goban .row li.hoshi::after {
        content: '';
        display: block;
        position: absolute;
        top: 50%;
        left: 50%;
        margin-top: calc(-.105em - 1px);
        margin-left: calc(-.105em - 1px);
        width: .21em;
        height: .21em;
        border-radius: .21em;
        background: #5E2E0C;
    }

**Comment by yishn** [comment]
Oops, I messed up the `margin-top` and `margin-left` properties above, it should be `margin-left: calc(${-x/2} - 1px);` instead of `margin-left: calc(${x/2} - 1px);`. I've corrected it.

**Comment by yishn** [comment]
For example, if `x = 6px`, use:

~~~css
.goban .row li.hoshi::after {
    width: 6px;
    height: 6px;
    margin-top: calc(-3px - 1px);
    margin-left: calc(-3px - 1px);
    border-radius: 6px;
}
~~~
