### ISSUE TITLE
"Remember geometry and state" button

### ISSUE THREAD

**Issue by Thegoban** [yishn/Sabaki#193]
I would put a new feature somewhere. a buton or a menu in wich you can save the current state of the aplication (geometry of the window, if the console or tree are deployed... so you have to never fight again minutes to put the things on the screen as you want. It would be nice if it could store at least tree configs at the touch of a button you can put it small in the top left corner, but if your boss have just left... press the button and play bigger in the middle of the screen... and now you need to edit something... select the one maximized with the tree deployed and the editting tools. 

I edit this because today I´m inspired hehehe.
don´t know the dificulty, BUT, your app is very modern looking, and it worths it:

No need for a button and forget about the position on the screen, you can change between the three (or more) "states" of the app by shaking it by the title bar!!

**Comment by Thegoban** [comment]
yess, yes you are right, good filosophy keeping things simple. Thats a cross platform software, but, if it is not too much effort in it... one button (or submenu) letting you switch between configurations is intuitive and simple in the user side... one button stores the state, the other switches it on... for example

**Comment by apetresc** [comment]
Use a window manager like [i3](https://i3wm.org/) and you'll get this feature for _every_ application you use, including Sabaki ;)

**Comment by Thegoban** [comment]
ohhh, yes... in Linux you can do almost anything... but no idea how windows works.... in linux Iuse a much more rudimentary devilspie... I´ll I3 give  of  an oportunity, the windows side is other thing
