### ISSUE TITLE
Making background resizable.

### ISSUE THREAD

**Issue by Thegoban** [yishn/Sabaki#196]
Good night... or good whatever time is there...
I´m making a theme, It´s simple as my skills but... I´m very happy whith the result!

To be honest the background chosen for the original theme is superb!, and I would´t recommend anybody to use mine... but I hope to end up whith all original parts or collecting them from other sources.  

So, my last issue is about background resizing... last background I´m playing with requires not to be static but to get resized in the same proportion as the goban... is it possible?... 

giving the solution is not as important as to know where to look, there are files that appear not to be present on my system... but they certenly are! as Sabaki starts normaly when deleting stile.css...  where the **ll (sorry) that config files that Sabaki must be reading to start up with original configuration are? probably is worth taking a look at them.

PS: At the moment I´m in a Win machinne, ahh, and thank you! ;)

**Comment by Thegoban** [comment]
I´m thinking about what I´m asking and not sure I´m explainin myself... or even if I´ve understood what I need, sorry.

**Comment by apetresc** [comment]
Hehe, welcome to the not-so-wonderful world of CSS :) Looks like you figured it out, but for future reference, [this is the link](https://css-tricks.com/almanac/properties/b/background-size/) I most often refer to when doing background magic in CSS. Hope it helps you next time!
