### ISSUE TITLE
AB tags don't accumulate

### ISSUE THREAD

**Issue by dfannius** [yishn/Sabaki#197]
I just opened the SGF file http://lifein19x19.com/forum/download/file.php?id=2310 in Sabaki 0.30.0, and many Black stones are missing from the initial position (you can see the file displayed in Eidogo at http://lifein19x19.com/forum/viewtopic.php?p=119544#p119544).

Studying the SGF file, my guess is that the second AB tag (containing only `[ic]`) is blowing away the first AB tag (containing `[pp][pn][qq][pj][pd][fc][db]`) instead of adding to it. I looked briefly at the SGF spec but couldn't tell whether AB tags are supposed to accumulate or replace earlier ones. In any case it seems that at least one other program (the file says it was created with MultiGo) assumes that they accumulate. I believe that I have opened the file in CGoban before and it loaded as intended.

Presumably this is the case with AW tags as well.

**Comment by fohristiwhirl** [comment]
Strictly, the SGF is faulty, there should be zero or one AB tags in the node, never two. But concatenating the lists would be reasonable, if possible...

**Comment by fohristiwhirl** [comment]
Looking at the preact branch, in _parseTokens() there is this:

    node[id] = []

I suspect if this became:

    if (node[id] === undefined) {
        node[id] = []
    }

That might be good enough...
