### ISSUE TITLE
Graphical board/stones customization interface

### ISSUE THREAD

**Issue by Seth-Rothschild** [yishn/Sabaki#198]
I'd be interested in working on this. I don't have fixed ideas for how it should work but the main feature should be a way to add images for stones/board/background inside of Sabaki.

**Comment by Seth-Rothschild** [comment]
I'd be interested in working on this. I don't have fixed ideas for how it should work but the main feature should be a way to add images for stones/board/background inside of Sabaki.

**Comment by yishn** [comment]
With CSS the user can override any existing styles to customize Sabaki's appearance. This does not only apply to stone/board/background images, but also board markers, colors, stone shadow, etc... 

My idea is this: I really like the idea of 'Sabaki themes'. Ideally, someone writes a userstyle with meta info and packages that into an [asar][1] archive, a 'Sabaki theme'. Sabaki lets the user install themes (i.e. by copying the asar archive into its config folder), manages them, and lets you switch from one theme to another instantaneously. 

The reason why using an asar archive is a good idea is that Electron treats asar archives as folders, so we don't need to extract the archive.

We can also write a small tool that lets users create their own Sabaki theme by providing stone/board/background images.

What do you think?

[1]: https://github.com/electron/asar

**Comment by Seth-Rothschild** [comment]
An asar archive seems to be a sound mechanism for electron though I'm wondering if it's wise to only be able to set  all customization aspects together. That is, it might be useful for users to mix and match boards, stones and backgrounds (or other customizations?) without having to make an entirely new theme each time. 

I claim there should be a tab in the preferences pane with 5 options
1. White stone set (i.e. read the .random images too)
2. Black stone set
3. Board
4. Background
5. Theme (as a catch all for markers shadows etc)

There might be a technical reason for not doing this that I'm not seeing, but morally it seems like the right kind of thing. For example, it's not clear to me why anybody would use the [letters piece theme](https://twitter.com/lichessorg/status/770653759118639104) in lichess, but it feels right that I could use that with a purple board without any hassle if I wanted to.

**Comment by ParmuzinAlexander** [comment]
Switch themes in sabaki it is good. But now there is one problem, need customize other elements like lines, coordinates, tools and border. I think need to remove border and make lines, coordinates, tools simple black, it looks like real goban, all go servers and sgf viewer.

**Comment by yishn** [comment]
@ParmuzinAlexander It is possible to change all of these things with a userstyle. This is not the issue to discuss personal tastes.

@Seth-Rothschild I do think that letting the user override images in the theme is a good idea.

**Comment by Seth-Rothschild** [comment]
Here's how I'm thinking of implementing it. Thoughts and suggestions would be helpful.

- Make a new tab in the preferences drawer for all of these settings
- Top option on the page is a place for the user to set their "themes directory"
   + This would replace the ~/Library/Application Support/Sabaki kind of thing currently in userstyles
   + There might be another obvious way to avoid OS specific code?
- There are five (as above) "select" tabs where the only default choices are "default" and "new"
   + default will be a new archive of the current theming info
- The "new" option
   + should be able to take in a folder of png files
   + an existing asar archive
   + will create a new option in a given tab

I'm pretty uncertain about implementation, particularly my last item. For one, I think it might require us to demand that stones/board/background have standard names in every theme. Then if the user says "mytheme.asar has black stones" we would be able to pull out all of the black stone png files quickly. Thoughts?

**Comment by yishn** [comment]
> * Top option on the page is a place for the user to set their "themes directory"

I think the "themes directory" should always be `{config folder}/themes` or something like that. IMHO, letting people set the theme folder is unnecessary. To get the config folder, you can use the `setting` module:

~~~js
const {setting} = sabaki.modules
const folder = setting.userDataDirectory
~~~

Maybe we don't need to extract the images from themes and just let the user *override* the stone images? So we have four text boxes, one for each image path, and a select box for choosing the theme. For example, if we have the following settings

~~~
            Theme: Subdued
White Stone Image: (Empty)
Black Stone Image: path/to/blackstone.png
      Board Image: (Empty)
 Background Image: path/to/bg.png
~~~

we would use the CSS in the 'Subdued' theme (including its stone/board/background images) and add [additional CSS](https://github.com/yishn/Sabaki/wiki/Userstyle-Tutorial) to override the black stone image and background image. This way, the user can change the theme without losing his custom supplied black stone/background image.

We can add an 'Install Theme' button. The user can select an asar archive and Sabaki can copy the archive into the theme folder.

**Comment by Seth-Rothschild** [comment]
That sounds like a much better plan on all counts. I'm vaguely worried about how to implement having a set of white stones (i.e. the .random classes) but that's certainly not urgent. 

Maybe accepting a path to a folder of .png images?

**Comment by Seth-Rothschild** [comment]
This is coming along slowly but honestly better than I expected given my total lack of prior knowledge. See [here](https://github.com/Seth-Rothschild/Sabaki/tree/BoardCustomizationMenu) for the branch as it stands. Two short notes:

1. I'm not certain I know how to deal with conditional additional css. I currently have paths stored in the local settings.json (I can get at them with settings.get(id)) but I'm not sure how to access that from css (or write the css inside of javascript). Something like insertRule seems promising, but the literature on that seems out of my current abilities.

2. I've tried my best to localize my changes so that it's easier for y'all to check if I'm doing things terribly and give suggestions on better methods. I've constrained my css changes to the top of index.css (they can be moved later) and the vast majority of my preferencesdrawer changes into a new class VisualTab.

3. Here's a picture of what it looks like so far.
<img width="1181" alt="preview" src="https://cloud.githubusercontent.com/assets/27442755/25653168/adbefa80-2fb9-11e7-9417-06e50fff97c5.png">

**Comment by yishn** [comment]
It looks good! 👍 Regarding 1: The custom userstyle is added in the [`App` component](https://github.com/yishn/Sabaki/blob/master/components/App.js#L2128); we can add custom CSS after it using a `<style>` tag and [JavaScript template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals):

~~~js
h('style', {}, `
    .goban li.sign_1 .stone img {
        background-image: url('${blackStonePath}');
    }
`)
~~~

Regarding 2: Git keeps track of all changes for us, so you don't need to worry about it. 😃

**Comment by Seth-Rothschild** [comment]
@yishn That was exactly what I was missing. As always the most recent version is [here.](https://github.com/Seth-Rothschild/Sabaki/tree/BoardCustomizationMenu) 

The list of things that are not yet working is fairly small now: 
+ actually copy the result from the `showOpenDialog` to a given path. I have the path for where it's going and where it's from in the event, but I'm having trouble using fs to copy .asar archives. It seems like `fs-extra` might be useful?
+ remove theme functionality: I'm not sure how the user should interact with this.
+ `href: setting.get('custom_theme') + '/styles.css` needs to not be that, but I'm not sure how to make `path.join` work in that context

Things that are new since yesterday:
+ The CSS for the stones and background now is customizable
+ You can select multiple stones and it will use .random
+ You can load .asar themes from a select dropdown

![image](https://cloud.githubusercontent.com/assets/27442755/25753682/7e79b8d2-318a-11e7-8aae-1a82fb038bfb.png)

**Comment by yishn** [comment]
@Seth-Rothschild Thanks for keeping us posted! 

* Electron patches the `fs` module so that it treats asar archives as folders. Electron provides the `original-fs` module to let you treat them as files, [see the documentation](https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md#treating-an-asar-archive-as-a-normal-file).
* Optimally, themes should have a `package.json` with meta information such as theme name, version, author, website, etc... Sabaki would show the information of the current theme in the preferences drawer. Then we could add a button 'Remove Theme' right beside the theme information. It should change the current theme to the default one and remove the corresponding asar archive.
* Does `path.join(setting.get('custom_theme'), 'styles.css')` not work?

**Comment by Seth-Rothschild** [comment]
Thanks so much! 1 and 3 are done and I'm fairly uncertain about my ability to do 2 with my current knowledge. 

I think the content of my BoardCustomizationMenu branch is close to as far as I can take it myself. What's standard operating procedure now?

**Comment by yishn** [comment]
It would be great if you could send in a pull request.
