### ISSUE TITLE
Option to disable mouse scroll navigation

### ISSUE THREAD

**Issue by raspingbard** [yishn/Sabaki#200]
When playing games against engines like Leela or Pachi, the mouse scroll wheel on the Mac is extremely sensitive and can inadvertently scroll back a number of moves prior to the click.  It then takes a bit of effort to delete the errant move and resume the game.  I'd like to see the mouse scrolling automatically disabled during game play (or at least provide a preference to disable it).  Thanks.

**Comment by yishn** [comment]
By 'game play' do you mean 'when an engine is attached'?

**Comment by raspingbard** [comment]
Yes, I primarily mean when an engine is attached.  Although, I notice the problem also exists with no engine attached, e.g. reviewing a game while entering variations.

**Comment by yishn** [comment]
So what you really want is just an option to turn off navigation by mouse wheel in all modes?

**Comment by raspingbard** [comment]
Yes, I believe so.  Navigation by the mouse wheel is so quick that I don't think it is even useful in its present state.  You could just disable the mouse wheel only for navigation, while leaving it enabled in the GTP console and Tree panels.

**Comment by yishn** [comment]
Perhaps the real solution to this problem is to make the mouse wheel navigation less sensitive, rather than to disable mouse wheel navigation altogether?

**Comment by raspingbard** [comment]
Yes, that might work.  Or, perhaps a slight delay.  The biggest problem I have is that right before I click the mouse, the game scrolls backward 5 or 10 moves, and then the click creates a new variation.

-Eric

**Comment by yishn** [comment]
I've released a new version of Sabaki (v0.30.2) with reduced mouse wheel navigation sensitivity. Let me know if it is helpful to the issue.

**Comment by raspingbard** [comment]
Yichuan,

Excellent!!  This fixes the issue I was having.  I played two games with Leela and didn’t experience a single roll-back.  Thanks for your quick response!

Regards,
-Eric
