### ISSUE TITLE
The application "Sabaki" can't be opened. (on macOS Sierra)

### ISSUE THREAD

**Issue by CamusLee** [yishn/Sabaki#201]
Hi Yishn,

I downloaded the release (0.30.1), but I got an error message (The application "Sabaki" can't be opened. ) when I run it on my MacBook Pro (macOS Sierra) after extracted the release package (sabaki-v0.30.1-mac-x64.7z).

Is there anything I missed?
Thank you.

Camus

**Comment by CamusLee** [comment]
I got the failed reason: I extracted the release package by The Unarchiver.

**Comment by CamusLee** [comment]
I found the reason, I extracted the release package by The Unarchiver.

**Comment by sebsel** [comment]
Can I ask why the export target is .7z? A .zip can be opened by macOS without extra dependencies and I believe a .gz would be fine too, but .7z is a bit non-standard.

**Comment by yishn** [comment]
7z gives the best compression in terms of size.
