### ISSUE TITLE
Can't set white rank

### ISSUE THREAD

**Issue by fohristiwhirl** [yishn/Sabaki#202]
I can't seem to set the white rank. While I haven't really tried to understand the code, there's a [typo](https://github.com/yishn/Sabaki/blob/a48c6a4752076465b32eefb462f98092ae9806ef/components/drawers/InfoDrawer.js#L121) in InfoDrawer.js that's probably related, "whiteRanke" instead of "whiteRank".

**Comment by yishn** [comment]
Good catch!
