### ISSUE TITLE
Request: Add command to pause game

### ISSUE THREAD

**Issue by raspingbard** [yishn/Sabaki#205]
This is a request to add a Pause or Pause Game command to the Engines menu (or Play menu).  I realize that I can stop the engines by detaching them and then re-attaching them later, but it would be a lot easier to have a Pause command.  (The command might toggle to Resume or Resume Game when in the paused state.)

**Comment by yishn** [comment]
I'm not sure what the pause command is supposed to do?

**Comment by raspingbard** [comment]
If an engine match is in progress, the Pause command would temporarily suspend the engines (by possibly detaching them in the background).  This will free up the CPU / GPU's on the machine for other tasks.

Also, when playing against an engine, Leela and Pachi (and possibly other engines) go into “pondering” mode while waiting for a move. Again, the Pause command would free up the CPU.
