### ISSUE TITLE
Minor issues with SGF format

### ISSUE THREAD

**Issue by raspingbard** [yishn/Sabaki#206]
When saving a game having no handicap, Sabaki will output the properties AB[ ] and HA[0] in the game header.

First issue: When loading this file into Leela 0.9.0, the AB[ ] property will cause Leela to lose the first black move.  Admittedly, this is a bug in Leela, but it would be good to remove the null AB property from Sabaki.

Second issue: HA[0] doesn’t seem to cause any problems with other apps, but the SGF guide at red-bean says for this property: Use integer values greater zero, e.g. "1", "5" or "9"

**Comment by fohristiwhirl** [comment]
I don't seem to get the this AB[] nor HA[0].

**Comment by yishn** [comment]
@raspingbard Can you give instructions to how to reproduce this? I don't get `AB[]` or `HA[0]` either.

**Comment by raspingbard** [comment]
I've narrowed down the repro case to where you must first have a game loaded that was played with a handicap.  

These steps will also do it:
1) Click File > New.
2) Change the Handicap to "4 stones".
3) Change the Handicap back to "No stones".
4) Click File > Save As.

**Comment by fohristiwhirl** [comment]
I think setGameInfo() needs a check for whether handicap === 0 and act accordingly.

Approximately [here](https://github.com/yishn/Sabaki/blob/8d0e2d41cbf75f19388ff4bf38cf4da7bcaf366a/components/App.js#L1408).
