### ISSUE TITLE
Sabaki rollbacks to original comments when saving at Edit Mode on macOS

### ISSUE THREAD

**Issue by CamusLee** [yishn/Sabaki#209]
Hi Yishn,
I go into Edit Mode to update the comments, before I leave the Edit Mode, I use the "Command + S" to save the updates, but the comments go back to the original version. I have to leave the Edit Mode first, then I can save the updates by using "Command + S".
I think it's a bug.

Camus

**Comment by fohristiwhirl** [comment]
Same applies to the Info Drawer. In that case, though, Sabaki doesn't yet know whether you'll click OK or Cancel...

Perhaps saving should just accept the state of whatever drawer is open and indeed close the drawer / comment state.

**Comment by yishn** [comment]
I would say the behavior in the info drawer is intended. But the text in the comment box should be applied to the game tree automatically, so it's a bug. Currently, Sabaki applies the text with the `onChange` event which fires when the text box loses focus.
