### ISSUE TITLE
Save with given node as root

### ISSUE THREAD

**Issue by dfannius** [yishn/Sabaki#214]
I often have a large SGF file corresponding to a whole game with many variations, or a joseki tree, and would like to export a portion of it, just everything below a given node, so that the exported SGF file starts with the given node's position. This would require removing everything above that node in the tree and doing any other initialization in that node that was previously implicit (e.g., place all the stones on the board, update number of captures).

I'm sufficiently interested in this feature that I might try to work on it myself.

**Comment by yishn** [comment]
Sabaki has the ability to 'flatten' a node that does what you described, I think. Use 'Edit' > 'Flatten' or 'Flatten' in the context menu in the game tree.

**Comment by dfannius** [comment]
Ah, so it does! For some reason I thought that Flatten removed variations as well, but I should have actually tried it. Great! Now I just have to remember to not Save and blow away my file with the full tree. :)
