### ISSUE TITLE
sabaki v0.30.2 is crashing in windows

### ISSUE THREAD

**Issue by hayrikilic** [yishn/Sabaki#215]
Hi,

I get the error msg (attached screenshot) just after starting the program. 
![image](https://cloud.githubusercontent.com/assets/28563167/25848270/464af094-34c2-11e7-85f5-e8155f7a7b63.png)

Regards,

**Comment by yishn** [comment]
This has been fixed in master. To fix this temporarily, make sure you have Internet connection or disable automatic update checking.
