### ISSUE TITLE
sabakitheme.asar extension not visible from add themes OSX

### ISSUE THREAD

**Issue by Seth-Rothschild** [yishn/Sabaki#221]
Tried installing photorealistic theme - the `extensions: ['sabakitheme.asar']` in preferences drawer is excluding it. Could be related to [this electron issue](https://github.com/electron/electron/issues/2525) about using dots and wildcards in extension names on certain operating systems.

FWIW I think it's probably fine to allow any asar with `filters: [{name: 'Sabaki Themes', extensions: ['asar']}]`. If a user *really* wants to try to load up something that's not a theme that's their prerogative.

**Comment by yishn** [comment]
Good catch! It's weird, because it works on Windows. It's most likely a bug in Electron.
