### ISSUE TITLE
Adjustable size for annotation symbols

### ISSUE THREAD

**Issue by raspingbard** [yishn/Sabaki#233]
The size of the annotation symbols in the comments section seem a bit too small on my large 27" screen.  Maybe these could be hooked to the font size preference (requested in another issue).  Or, you could display them as larger symbols somewhere below the comments.  (I note that SmartGo Kifu for iPad displays these annotations as very large symbols over the go board.  Although, this placement can be a bit distracting.)

**Comment by yishn** [comment]
I think the annotation icon size should adapt to the font size (see #232), so I'm closing this.
