### ISSUE TITLE
Failure to save after adding annotations

### ISSUE THREAD

**Issue by tuirgin** [yishn/Sabaki#238]
After adding an annotation from the menu—e.g. "Doubtful move" or "Good for White"—Sabaki hangs while saving. The cursor switches to the OS's "busy" cursor and all menu items are grayed out except for "File > New Window" and "Help > Check for Updates". I've left it hanging the entire time it's taken to write this up, with no changes in state. It is possible to launch new windows which work as expected.

To reproduce:
1. Create a new game.
2. Add a move.
3. Add an annotation to the move.
4. Attempt to save.

The behavior is identical for Sabaki v0.30.3 on both Linux and Windows using the provided x64 Linux appimage and the Windows installer.

![20170525234051-764x629](https://cloud.githubusercontent.com/assets/97160/26479787/e1e68dae-41a3-11e7-861b-63e8b537c2ca.png)

**Comment by fohristiwhirl** [comment]
I believe Sabaki is getting trapped in stringify() somehow.

**Comment by fohristiwhirl** [comment]
It crashes here:

https://github.com/yishn/Sabaki/blob/a48c6a4752076465b32eefb462f98092ae9806ef/modules/fileformats/sgf.js#L261

Wrapping in a try I get:

TypeError: node[id].map is not a function.

**Comment by fohristiwhirl** [comment]
So the problem is node[id] === 1 when it should be node[id] === [1]

**Comment by fohristiwhirl** [comment]
So probably App.js at lines [1504](https://github.com/yishn/Sabaki/blob/master/components/App.js#L1504) and [1513](https://github.com/yishn/Sabaki/blob/master/components/App.js#L1513) need to be this?

node[data.moveAnnotation] = [moveProps[data.moveAnnotation]]

node[data.positionAnnotation] = [positionProps[data.positionAnnotation]]

**Comment by yishn** [comment]
Thanks guys! This is a very severe bug...
