### ISSUE TITLE
Suggestions for more engine backend 

### ISSUE THREAD

**Issue by abhi18av** [yishn/Sabaki#240]
Hello @yishn 

First off, you're really awesome for building this - thanks a ton man :+1:  :smile: !! Your code style is also a delight to read :)

Btw,  I wanted to point out that there are two more open source backends that you can easily integrate within the package as a whole for a great experience.

https://github.com/ujh/iomrascalai
https://github.com/brilee/MuGo

These two do provide GTP and are fairly cross platform with liberal licenses.

**Comment by yishn** [comment]
Thank you for your praise! I'd like to keep Sabaki as minimal as possible, but you're free to add [instructions][1] to the documentation as to how to integrate the engines you mentioned.

[1]: https://github.com/yishn/Sabaki/blob/master/docs/guides/engines.md
