### ISSUE TITLE
icns2png and gm error under Linux

### ISSUE THREAD

**Issue by fishcu** [yishn/Sabaki#241]
I cannot successfully run the "npm run dist:linux" command under Ubuntu. There is an error:
Unhandled rejection Error: Exit code: ENOENT. spawn icns2png ENOENT

I can fix it by running "sudo apt-get install icnsutils". I then get the same error with "gm" instead of "icns2png". I can fix that again by installing graphicsmagick. The proper way to fix it seems to be the same as here, to mention these as dependencies: https://github.com/electron-userland/electron-builder/issues/1407

**Comment by yishn** [comment]
I'm closing this since it's an electron-builder problem just as you mentioned.
