### ISSUE TITLE
Keyboard game navigation

### ISSUE THREAD

**Issue by mlopezviedma** [yishn/Sabaki#244]
It would be useful to have shortcut keys for going to previous/next game.

**Comment by yishn** [comment]
What shortcuts do you suggest?

**Comment by mlopezviedma** [comment]
I suggest Ctrl+Home and Ctrl+End. PageUp and PageDown keys are also not used, I don't know which one is better.

**Comment by yishn** [comment]
I don't think <kbd>Ctrl</kbd>+<kbd>Home</kbd> and <kbd>Ctrl</kbd>+<kbd>End</kbd> are appropriate. How about <kbd>Ctrl</kbd>+<kbd>PageUp</kbd> and <kbd>Ctrl</kbd>+<kbd>PageDown</kbd>?

**Comment by mlopezviedma** [comment]
I buy that one :)

**Comment by mlopezviedma** [comment]
Excellent, thanks a lot, @yishn ! Keep up the great work!
