### ISSUE TITLE
Show engine name and version

### ISSUE THREAD

**Issue by mlopezviedma** [yishn/Sabaki#245]
Sabaki can get engine info through the `name` and `version` GTP commands.

**Comment by yishn** [comment]
Where do you want these information shown? Currently Sabaki displays the manually assigned name instead of the official name. This is useful because you can add the same engine with different arguments and assign different names to them to differentiate between them.

**Comment by mlopezviedma** [comment]
Yeah, I was thinking only about showing that info only in the menu (when choosing an engine) for reference.

**Comment by gcp** [comment]
>This is useful because you can add the same engine with different arguments and assign different names to them to differentiate between them.

Maybe the manually assigned name could be automatically filled in from the automatic name from GTP, the first time the engine path is specified. This still leaves the user free to modify it.

**Comment by yishn** [comment]
This would require running the executable without the user explicitly attaching the engine. I'm not sure I want that. Now that I think about it, this whole proposition seems impossible. Sabaki can't run every engine each time it starts to determine their names and versions.

**Comment by gcp** [comment]
I guess another issue is that you actually need the command-line parameters to enable GTP mode to be set before this could even work.

**Comment by yishn** [comment]
Good point; I'm closing this as wontfix.
