### ISSUE TITLE
Cannot get Ray to work with this at all. 

### ISSUE THREAD

**Issue by davidye2020** [yishn/Sabaki#247]
Calculates but won't put anything on the board. Almost like it cannot interface correctrly. 

https://github.com/zakki/Ray

I get Leela GTP to work, but cannot get Ray to work.

**Comment by yishn** [comment]
Can you see something in the GTP console?

**Comment by davidye2020** [comment]
Here is screenshots

https://imgur.com/a/vTKTH

**Comment by yishn** [comment]
It doesn't look anything like GTP in the second screenshot. Are you sure Ray supports GTP?

**Comment by davidye2020** [comment]
I'm sure Ray supports GTP, it in fact ONLY supports GTP and nothing else. I can get Ray to work in GoGui just fine. 

Also, a while earlier, in the Sabaki with GTP console view, I could actually SEE Ray do the calculations and the TGR1 0.1% percentage factor counting up etc in the actual Sabaki with GTP console view itself!! and these values coming from Ray itself... but at the very end when it finishes its calculations and supposed to output and place a stone, nothing happens and the entire Sabaki application just hangs, my CPU goes to idle, and I have to force kill the application because it just hangs there doing absolutely nothing. 

I even tested with "--gtp" and "--mode gtp" but that then gives error of "connection error", thus proving Ray does not need any other extra parameters to turn it on since by Default it is turned on for GTP.

**Comment by davidye2020** [comment]
Nevermind I got it to work. Seems like my computer was infected by some kind of virus.
But its all good now.

https://imgur.com/a/vTKTH
