### ISSUE TITLE
Copy engine name to player name field

### ISSUE THREAD

**Issue by raspingbard** [yishn/Sabaki#248]
In the Game Info panel, when you select an engine to play, Sabaki should copy the engine name from the menu into the player name field.

**Comment by mlopezviedma** [comment]
Only if the name is empty (not manually set) in my opinion.

**Comment by yishn** [comment]
Say you only have one engine attached. Even if you attached this engine to one colour, say black, Sabaki allows the user to generate a move on white's turn, by reattaching the engine to white. If people think Sabaki fills in the name for you automatically, they would expect Sabaki to change player names when reattaching. But this behaviour might not be desired.

**Comment by raspingbard** [comment]
Replying to mlopezviedma's comment: If you changed your mind and selected a different engine, I think you would still want it to copy the new engine name.  Perhaps Sabaki could detect manual changes to the player name and not do the copy in that case.

Replying to yishn's comment: In my experience playing chess engines, when you force the computer to generate a move, it essentially swaps the sides of the players for the rest of the game, or until you generate another move.  So, I would expect Sabaki to just swap the player names when you generate a move. This seems natural to me.

**Comment by yishn** [comment]
This sounds reasonable.

**Comment by yishn** [comment]
@raspingbard What about the following scenario: Say, we have a record of a game with names already saved on them and want to consult an engine for better moves. To do that we attach an engine as white. Since the names are already filled in, Sabaki won't override them. Now we browse through the game and want to find a better move for black. We press <kbd>F5</kbd> to generate a move on black's turn. 

In this scenario, flipping the player names is not desirable, isn't it?

**Comment by raspingbard** [comment]
Hi Yishuan, I checked the chess software I use and it requires you to start a new game if you want to play against the engine from a particular starting point in a game review.  Actually, most chess software, as well as Leela (the application), have an Analysis feature that runs the engine in the background and offers advice while reviewing a game.  It does this by highlighting the suggested squares or points on the board and optionally showing a list of moves in a separate window or pane.

Ideally, Sabaki would provide a similar Analysis feature.  Without this feature, the management of player names becomes a bit difficult.  I think you have three options:

Option A – don’t change the player names at all (except when the user selects an engine from the dropdown menu).

Option B – detect whether the user is playing a game or reviewing a game, and only swap player names for the first case.  (I don’t know if this condition can be safely detected in Sabaki.)

Option C – always swap the player names when the user generates a move (F5).

If option B is not practical, then I think option A is best.  The user must manually change the names if sides are swapped.  I don’t think option C is good for the reasons you mentioned.

(I noticed that Sabaki inserts the engine name in the player field when a move is generated.  I’m not sure this is a good idea with any of the above options unless the player name is stored on a per move basis, which it is not in the SGF file.)

**Comment by yishn** [comment]
Currently, Sabaki will display the name of the engine in the player bar in a monospace font if an engine is attached. On detaching the engine, the actual player name is displayed. This does not mean that Sabaki changes the player name in the SGF file.

Thanks for the detailed analysis! You're right that option B is inpractical...

**Comment by yishn** [comment]
Option A is now implemented.
