### ISSUE TITLE
Windows 10 -> link Sabaki with SGF Files

### ISSUE THREAD

**Issue by MrNowName** [yishn/Sabaki#249]
Dear yishn,

your program is really awesome.
I love it!
Thanks for that!

My problem is I wanna link all my sgf or other GO Files with Sabaki. So when I click them it automatically opens up. But I always get a "wrong parameter" error.
Should this work? Or is it not supposed to work?

Thanks in advance!

**Comment by yishn** [comment]
It is supposed to work, of course. Can you send a screenshot of what error you get?

**Comment by MrNowName** [comment]
Of course :) 
Here you go!
http://imgur.com/a/ouR8A

**Comment by MrNowName** [comment]
I just uninstalled it and then reinstalled it.. i connect it again to the SGF Files.. now it seems working :) This can be closed! 👍 Thanks anyways!

**Comment by yishn** [comment]
I'm glad this is resolved!
