### ISSUE TITLE
Add bot review capability

### ISSUE THREAD

**Issue by raspingbard** [yishn/Sabaki#252]
There’s a fairly new Python project in GitHub called [GoReviewPartner](https://github.com/pnprog/goreviewpartner/) that’s been getting a lot of buzz recently.  You can read more about it [here](https://lifein19x19.com/viewtopic.php?f=9&t=14050&start=0).

What the tool basically does is run one of the bots (Leela, Ray, or GnuGo) in batch mode on an SGF file and then add the primary variations recommended by the bots to each move.  The number of moves in each variation can be customized at the start of the run.  This usually produces a fairly large game tree, but the end result of being able to review games in this manner is really great!

This is a request to add similar functionality to Sabaki, which has a **vastly** improved interface over GoReviewPartner, and would raise the awesomeness of Sabaki to the next level.

**Comment by yishn** [comment]
What's wrong with running GoReviewPartner and then opening the resulting analysis file with Sabaki? AFAIK, GoReviewPartner produces a valid SGF file which Sabaki has no problems opening.

**Comment by raspingbard** [comment]
Yes, that is certainly possible.  But if you’re using a Mac, you need to know how to download the source code from GitHub, open the Terminal app, then run command lines in Python.  Not exactly user-friendly.  The user interface of GoReviewPartner is also very crude.  It would be nice to do the analysis and review together seamlessly in one modern app.

**Comment by yishn** [comment]
Please contact the author of GoReviewPartner for how to make it more user-friendly. Sabaki is an SGF editor only, and I don't think this feature has a place in it.
