### ISSUE TITLE
Sabaki doesn't send pass command to engines

### ISSUE THREAD

**Issue by Coelomata** [yishn/Sabaki#255]
When playing against a bot, such as GnuGo, passing causes the engine to detach. When the engine itself passes, this does not seem to be a problem, only when I pass. This is with GnuGo set up as the wiki recommends, and this has happened on both Windows and Linux for me. The only workaround seems to be going to the menu bar, Engine>Attach, and then the bot will either pass or play. If it plays, I pass again, and same issue. Kind of tedious.

**Comment by mlopezviedma** [comment]
I confirmed that this issue is also present with Leela.

**Comment by yishn** [comment]
I can only confirm that Sabaki doesn't send a pass command to the engine as it should. However, I'm not experiencing any engine detachment.

**Comment by mlopezviedma** [comment]
I supposed it detaches because re-attaching it works, but I don't know how to notice if the bot is detached. On GTP console nothing appears when I pass.

**Comment by mlopezviedma** [comment]
That was fast! Thank you!
