### ISSUE TITLE
Strange behavior when cancelling illegal move

### ISSUE THREAD

**Issue by bcc32** [yishn/Sabaki#257]
When playing manually against an engine, if the human player attempts to make an illegal move (e.g., ko, suicide), then selects "Don't play", the human and computer players inexplicably switch sides and the computer is asked to generate the move that the human cancelled.

**Comment by yishn** [comment]
Thanks for reporting! I'm not encountering this issue. Which version of Sabaki are you using? Can you provide reproduction steps?

**Comment by fohristiwhirl** [comment]
Happens for me on almost-current. Make sure you click "Don't play". Reproduction:

* Load an SGF file like this and go to the end:

    (;GM[1]FF[4]CA[UTF-8]SZ[9];B[ai];W[ee];B[bi];W[ff];B[ci];W[fd];B[di];W[ge])

* Attach an engine as White
* As Black, try to make an illegal move
* Click "Don't Play" (important)

**Comment by yishn** [comment]
It seems that this issue has already been resolved in master. Most likely fixed by #255.

**Comment by fohristiwhirl** [comment]
Ah that is so, updating to the most recent build makes it go away.

**Comment by bcc32** [comment]
Thanks for the quick response. (I was using v0.31.1.)
