### ISSUE TITLE
Appimage prompts for desktop integration each time the app is launched

### ISSUE THREAD

**Issue by IDex** [yishn/Sabaki#258]
There should be a way to avoid this or disable it as it's an annoying hindrance that starts to get old by the 100th time.

**Comment by yishn** [comment]
I don't think I can do anything about that. Please contact the maintainers of AppImage instead.

**Comment by IDex** [comment]
AppImage maintainers told me you have severely outdated AppImage version and that AppImage allows you to easily fix this.

**Comment by yishn** [comment]
Do you have a link to the thread for reference purposes? Sabaki uses [electron-builder](https://github.com/electron-userland/electron-builder) to pack the binaries, so you need to contact them to update AppImage.

**Comment by IDex** [comment]
Here is the relevant IRC log
><IDe> An appimage is bugging me about some desktop integration feature every
      time I launch it. Is there a way to permanently decline the installation
      of icons etc?
<TheAssassin> IDe: hi
<TheAssassin> there should be two windows, one which asks you whether to
              integrate it, and one that asks you whether to ask you again
<TheAssassin> did you get the second, but ignored thetext?
<IDe> TheAssassin: I don't recall ever getting prompted with the second
      question. Is there a way to reset it?
<TheAssassin> IDe: well, honestly, the AppImage itself can contain _anything_
<TheAssassin> you'll have to gimme an example
<TheAssassin> or make a screenshot
<TheAssassin> "an appimage"
<IDe> Example of an offending appimage can be found here:
      https://github.com/yishn/Sabaki/releases/tag/v0.31.2
<IDe> TheAssassin:
<TheAssassin> dont call it "offending"
<TheAssassin> what is it even offending? there is no "standard"
<TheAssassin> confirmed
<TheAssassin> btw
<TheAssassin> IDe ^^^
<TheAssassin> looks like they're using a REALLY outdated version of the AppImage runtime
<TheAssassin> oO
<IDe> It offended me when it prompted for desktop integration for the 1000th time
<IDe> Is there a way to edit the image in question to not prompt?
<IDe> Is there a way to edit an appimage?
<TheAssassin> just came back
<TheAssassin> IDe:  sure
<TheAssassin> ./xxx.AppImage --appimage-extract
<TheAssassin> wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
<TheAssassin> chmod +x appimagetool-x86_64.AppImage
<TheAssassin> ./appimagetool-x86_64.AppImage squashfs-root xxx-new.AppImage
<TheAssassin> done.
<TheAssassin> I guess we have to make people update their stuff regularly.

I'll post an issue to electron-builder. Thanks!

**Comment by probonopd** [comment]
If you don't want to be asked about desktop integration, create one of these files:

- $HOME/.local/share/appimagekit/no_desktopintegration
- /usr/share/appimagekit/no_desktopintegration
- /etc/appimagekit/no_desktopintegration

Source code:
https://github.com/AppImage/AppImageKit/blob/master/desktopintegration#L174-L178
