### ISSUE TITLE
Cut'Copy'Paste does not have standard shortcuts

### ISSUE THREAD

**Issue by dwt** [yishn/Sabaki#259]
Hi there,

working with SGF variations would be much easier if cut'copy'paste would have the standard shortcuts.

Current behavior: No shortcuts are assigned to thsese on Mac OS.

Expected behavior: They should have command-x, -c, -v

**Comment by yishn** [comment]
Cmd-X/C/V are reserved for copying/pasting text.

**Comment by mlopezviedma** [comment]
How about Cmd-Shift-X/C/V?

**Comment by yishn** [comment]
<kbd>Cmd-Shift-C</kdb> is currently used for 'Toggle Coordinates'.

**Comment by dwt** [comment]
Sorry, could you explain why they are reserved only for copying text? Normally (on MacOS at least) that is not the case, there they are reserved for copying whatever is currently selected.

**Comment by yishn** [comment]
Basically, on macOS, there are menu items that are handled by the OS, such as 'Copy', 'Cut', and 'Paste', which have the usual keyboard shortcuts. AFAIK, they all handle currently selected text. The menu items that are responsible for copying/cutting/pasting variations are handled by Sabaki itself.

**Comment by Spoekenkieker** [comment]
**dwt is right:** on macOS, cmd+c, cmd+x, cmd+v handle **whatever is currently selected**.

**Comment by yishn** [comment]
In a perfect world, I'll grant you that. But within the limitation of Electron, I don't think this is easily, if at all, solvable. And as I explained here https://github.com/yishn/Sabaki/issues/260#issuecomment-317858011, Sabaki doesn't have the notion of selected nodes.

**Comment by dwt** [comment]
> In a perfect world, I'll grant you that. But within the limitation of Electron, I don't think this is easily, if at all, solvable. And as I explained here #260 (comment) <https://github.com/yishn/Sabaki/issues/260#issuecomment-317858011>, Sabaki doesn't have the notion of selected nodes.
> 

I gather that the code does not, but in the UI it certainly looks like a Node is currently selected - which is why cut/copy/paste seems to be so natural there.

Maybe it would be a nice extension to the code model to track that selection not only in the UI?

Best Regards,
Martin Häcker

**Comment by yishn** [comment]
Generally, selected things should be unselected when other things are selected. This is necessary if certain actions depend on the selected element. This is not the case with the nodes in the game graph here. And removing the highlight when, say, a text box is selected, is bad since you don't know at which node you are when editing comments.
