### ISSUE TITLE
[MacOS] cannot trigger 'Remove Node' via shortcut

### ISSUE THREAD

**Issue by dwt** [yishn/Sabaki#260]
I guess the problem is that it is bound to 'delete to the right' which is not a key a mac keyboard has, and the shortcut to generate (<command-shift-delete>) doesn't seem to trigger the shortcut.

I'd like to propose several alternatives:
* Switch the delete key, i.e. use <command-delete> instead of command-delete-to-right, so it can directly be triggered from a mac keyboard
* Consider to also loose the <command> prefix. The reasoning here would be that in SGF (perhaps just in editing mode) editing the SGF is like editing a text file. And there too you just use delete to delete what you have entered / selected, without adding the <command> prefix.
* Recognize <command-shift-delete> for this functionality. (I don't quite like this too much, as it's more keys than required, and I kind of like the analogy to a text editor.)

What do you think?

**Comment by yishn** [comment]
I guess we can change the shortcut to <kbd>Cmd+Backspace</kbd> on macOS.

> *   Consider to also loose the prefix. The reasoning here would be that in SGF (perhaps just in editing mode) editing the SGF is like editing a text file. And there too you just use delete to delete what you have entered / selected, without adding the prefix.

I'm not sure, there are just a lot of things you can remove in a setting like this. Remove board markers? Remove text? Remove meta information? Remove stone? (Note that "Remove stone" is not the same as "Remove node")

**Comment by dwt** [comment]
Well, I would guess that it should work the way the user sees it. That means, if the node graph shows a node as selected, then backspace should remove it. If you have different meta-information that could be removed, then you need to either show them as modifiers (then they shouldn't be removed by backspace but instead the whole node should be) or you show them as their own nodes. Then of course it makes sense to remove them as separate steps via backspace.

**Comment by yishn** [comment]
First of all, Sabaki doesn't even have the notion of 'selected' nodes, it only highlights the node you're currently at. The difference is, that if you select text or other stuff that are actually selectable, the current node is still highlighted.

There is also the following argument for having a dedicated keyboard shortcut for removing nodes: Imagine you're in the comment box, editing some comment text in a variation. Then you notice that you don't actually need that variation. In this case you can press <kbd>Cmd+Backspace</kbd> to remove the node. If <kbd>Backspace</kbd> is used to remove a node, you'll have to exit edit mode first to remove it.

**Comment by dwt** [comment]
Sounds not too unreasonable. I mean as long as there is a way to have keyboard shortcuts to do this it's a win.

On Mac OS generally this is handled with the first responder pattern, i.e. one view has the current 'keyboard shortcut focus', which means that it gets the first shot at handling menu commands like 'cmd-c/ -v / -x' and can then decide to decline handling them and instead hand them up the view hierarchy to someone who can. This means that copy/paste would be handled by the comment-field when you are working on the comments and handled by the node view when you last clicked on the node stuff (i.e. the text field doesn't have focus anymore).

**Comment by dwt** [comment]
thanks! :)
