### ISSUE TITLE
Disregard Go rules

### ISSUE THREAD

**Issue by spielstein** [yishn/Sabaki#263]
I would like to playtest other games playable on a goban. Is it possible to deactivate the automatic Go capture for that purpose? So only the automatic color change per turn is still provided (however this could also be parameterized somehow).

BTW: Very nice project.

**Comment by yishn** [comment]
Thank you! While this probably won't make it into Sabaki, it's easy to do it on your own: 

Fork this project and modify the `Board` class located in [`modules/board.js`](https://github.com/yishn/Sabaki/blob/master/modules/board.js#L381). Look for the function `makeMove()` and modify it to suit your tastes. To deactivate stone capturing, just remove [these lines](https://github.com/yishn/Sabaki/blob/master/modules/board.js#L389-L412) from it.

In fact, I did this once to my own fork of Sabaki to play Gomoku with my Gomoku engine that I've written some time ago.
