### ISSUE TITLE
Go engine interface for Web Mode

### ISSUE THREAD

**Issue by zakki** [yishn/Sabaki#264]
Is there any plan to add GTP interface for Web Mode?
I'm porting Go engine Ray to emscripten ( https://zakki.github.io/ray-web/ ), and I with there was pretty GUI.

**Comment by yishn** [comment]
There are no plans. I'm skeptical as how practical it would be. Something like this is quite big to download. Also it might not be the best to run something so computational expensive in the browser.

**Comment by zakki** [comment]
Yes, both download size and runtime footprint are heavy.
I try to look into this.

**Comment by yishn** [comment]
I'd like to keep the issue list as short as possible, so I'm going to close this. Feel free to reach out to me if you have a concrete plan.

**Comment by solohsi** [comment]
> I'd like to keep the issue list as short as possible, so I'm going to close this. Feel free to reach out to me if you have a concrete plan.

Is there any way to play/analysis with AI engine by using GTP in web version? Can we run a local AI engine on the servser?
