### ISSUE TITLE
Save SGF to local m/c possible?  also, Security concerns due to access to filesystem?

### ISSUE THREAD

**Issue by harryfearnley** [yishn/Sabaki#268]
The documentation seems to imply that one can save the SGF produced from the web version to one's local machine.  How do I do that (except by saving SGF to Clipboard, ...)?

Are there any security concerns, with Sabaki's (web based version) access (reading) from local filesystem?

Harry

**Comment by yishn** [comment]
Using the [`sabaki.saveFile()`](https://github.com/yishn/Sabaki/blob/master/docs/api/sabaki.md#sabakisavefilefilename) method you can let the user download the SGF file. It triggers a normal download file dialog on your browser, just like you can download any other file on the internet.

With [`sabaki.loadFile()`](https://github.com/yishn/Sabaki/blob/master/docs/api/sabaki.md#sabakiloadfilefilename-options) you can prompt the user to choose a file. The file is accessed using the [File API](https://w3c.github.io/FileAPI). The file won't be uploaded anywhere and is parsed directly in the browser. Only the file selected by the user can be accessed and system-sensitive files are not accessible at all as detailed in the [security & privacy considerations section](https://w3c.github.io/FileAPI/#security-discussion).
