### ISSUE TITLE
Such a good App, don't know why, I always cannot download down here, could you tell me whether other ways?

### ISSUE THREAD

**Issue by ReverseScale** [yishn/Sabaki#270]
Can ask you to send me a, MAC is good, really want to try, thank you very much.
ReverseScale@iCloud.com

**Comment by ReverseScale** [comment]
OK，I can download，If there is a computer game with good, AlphaGo access method

**Comment by yishn** [comment]
If you're looking for engines to play with, refer to the [docs](https://github.com/yishn/Sabaki/blob/master/docs/guides/engines.md). If you want to train your own DCNN à la AlphaGo, I suggest you take a look at [BetaGo](https://github.com/maxpumperla/betago).
