### ISSUE TITLE
"Something wierd happened"

### ISSUE THREAD

**Issue by GreenAsJade** [yishn/Sabaki#282]
I had minimised sabaki on my mac.  I think this happened upon maximising.

![screenshot 2017-09-15 21 06 40](https://user-images.githubusercontent.com/61894/30480626-d8f1e194-9a59-11e7-911a-244f54873bc7.png)

**Comment by yishn** [comment]
I tried the following with the latest version v0.31.2 on macOS Sierra:

1. Open Sabaki
2. Maximize window
3. Minimize window
4. Restore window

It works perfectly. Can you give reproduction steps?

**Comment by yishn** [comment]
Since there is no response, I'm going to close this.
