### ISSUE TITLE
Export game data in a form that can be used in typesetting programs

### ISSUE THREAD

**Issue by FelixBrendel** [yishn/Sabaki#283]
I sometimes want to print out go game records. When using `psgo` I can enter the game in this format:
```latex
\begin{psgoboard}
	\move{r}{16}
	\move{q}{4}
	\move{c}{17}
	\move{c}{4}
	\move{o}{17}
	\move{f}{4}
	\move{r}{3}
\end{psgoboard}
```

And will get a  pdf containing
![image](https://user-images.githubusercontent.com/5005975/30710770-e1af4766-9f06-11e7-9323-ba7883879666.png)

It would be awesome to be able to export the main / current variation in the game tree as a text in this format. What do you think?

**Comment by yishn** [comment]
This sounds like a very specific feature... Honestly, I think this should be something a standalone program could do.

**Comment by FelixBrendel** [comment]
I see. I thought Sabaki is about handling sgf files, maybe it can also export them to different formats.
If you do not want to add it, I will write a script to convert sgf -> latex :)

**Comment by yishn** [comment]
I have some vague plans of a future feature to export (or print) game records as SVG images. This would give me some freedom in how to render board markups. These vector images can not only be included in LaTeX files but also included in web pages, word processors, etc. Everywhere, basically.

So I'm closing this issue.
