### ISSUE TITLE
Sound enhancement

### ISSUE THREAD

**Issue by ParmuzinAlexander** [yishn/Sabaki#284]
How about adding options or enabled "sound on replay" (hand navigation)?
And add custom sound like themes?

**Comment by yishn** [comment]
As it has been discussed on the L19 forums extensively, I don't think sound on replay is a good idea. I don't have any plans (and frankly, I don't intend to have any) to let the user customize sounds. But if you have better sounds that can be used in Sabaki, feel free to send in a pull request.
