### ISSUE TITLE
What do you think if I change the UI color to this?

### ISSUE THREAD

**Issue by geovens** [yishn/Sabaki#285]
![test](https://user-images.githubusercontent.com/9478369/30811611-41ca4844-a23b-11e7-8265-261d3b2637e2.jpg)
The change is here: https://github.com/geovens/Sabaki/commit/1fc838b665f3297ed20de9e69cde26ff861ca4bd

I personally think that the all-black sidebars might be a bit confusing. There are small triangles here and there but it may take some time to understand that they are part of a scroll bar. And such things. If you don't like my change, how about at least giving the scroll bar of the gametree a slightly different color to show it's a scroll bar more clearly?

**Comment by yishn** [comment]
The colors look nice! Personally, I find the chromeless look of the standard theme quite elegant. Why don't you [create a theme](https://github.com/yishn/Sabaki/blob/master/docs/guides/create-themes.md) and submit it to the [theme directory](https://github.com/yishn/Sabaki/blob/master/docs/guides/theme-directory.md)?

**Comment by geovens** [comment]
I can pack changes that are outside styles.css in themes? I didn't know that.

**Comment by yishn** [comment]
Sure, just put those statements into your own `styles.css` to override the standard ones and pack it into your own theme.
