### ISSUE TITLE
Better integration with GTP engine results?

### ISSUE THREAD

**Issue by gxli** [yishn/Sabaki#286]
I realized that there is a lot of useful information in the GTP engine outputs, and my first thought is, would it be useful to put these into the game tree as comments? So after the engines have self-played for a while, we can go through the game tree to see what moves have been considered?

Another potentially useful feature is to display these potential moves on board while browsing through the game trees.

**Comment by apetresc** [comment]
What kind of integration is missing? Sabaki is already a very good GTP client.

**Comment by yishn** [comment]
@gxli I assume you mean the sort of functionality that [GoReviewPartner](https://github.com/pnprog/goreviewpartner) provides? I understand the appeal, but GTP engine outputs are not standardized, so it's hard for Sabaki to support every possible engine. I can only recommend using GoReviewPartner to generate an SGF file which Sabaki has no problems opening.

**Comment by gxli** [comment]
@yishn # thanks that works too. Besides the elegant GUI design, what I particularly like about sabaki + gtp engines is I can go through the game, let the engines play for a few moves, stop whenever I like, and browse through the game tree generated by the GTP engine later. This flexibility is not offered by GoReviewPartner yet.

Sabaki is already doing a nice job interpreting the GTP engine results: the GTP-console window allows me to browse through the GTP outputs, and it automatically marks the moves proposed by the engine on the board. However, it is difficult to browse through the already-long GTP output window to find out what did the engine say about a move.

A simple solution is to put the GTP output information, regardless of what they are, to the game tree as comments. This will make it much easier to find out what did the GTP engine say about a particular move. Since the comment section of the GTP-generated part of the game tree is empty, putting the GTP engine outputs there seems to be a good use of the space.

<img width="1348" alt="sabaki" src="https://user-images.githubusercontent.com/1741741/30831463-dafc1fe0-a247-11e7-8d9d-0cd48af4176d.png">

**Comment by yishn** [comment]
This actually sounds pretty nice! We could add a setting whether the user wants engine outputs be logged into the comment section or not.

**Comment by gxli** [comment]
thanks, that would be nice! it also leaves plenty of room for integration with GTP engines when the outputs have been standardized.

**Comment by aTan-aka-Xellos** [comment]
Hello! Thank you for this project!
Since my qyestion is quite similar I would ask here.
Is it possible to output results of GTP into log file? I haven't find such feature. How about adding it? 

P.S. proposed approach like on screen above have few issues:
- when long time setting is applyed - it won't be comfortable to scroll over it
- when pondering is on - output printed non-stop

**Comment by yishn** [comment]
> Is it possible to output results of GTP into log file? I haven't find such feature. How about adding it?

There's no such feature. Please open a new issue for that.

> P.S. proposed approach like on screen above have few issues:

I'm sorry, I don't understand your issues with the proposal, can you elaborate?

**Comment by yishn** [comment]
Check out [LeelaSabaki](https://github.com/yishn/LeelaSabaki), everyone!
