### ISSUE TITLE
Pass sgf path to CLI param

### ISSUE THREAD

**Issue by gaydenko** [yishn/Sabaki#288]
Hi! Haven't found a way to pass sgf path as CLI param. Are File/Open and Ctrl-O the only ways?

**Comment by yishn** [comment]
Sabaki should handle file paths as CLI argument... Can you post the full command that is not working and the OS you're using?

**Comment by gaydenko** [comment]
Hi! 
Linux is in use.
Sorry for noise - my fault. I have used (now commented out) wrong string to call Sabaki, but the last string does really work with `sgf` files containing spaces in the path.
```sh
#!/bin/sh

# /opt/Sabaki/sabaki $@
/opt/Sabaki/sabaki ${1+"$@"}
```
