### ISSUE TITLE
Anti Virus won't let me install the latest build

### ISSUE THREAD

**Issue by zwederevenge** [yishn/Sabaki#289]
It's says it found "Win32:Evo-gen [Susp]" and throws the file into quarantine. Didn't have any issues with v0.31.3

**Comment by yishn** [comment]
I've run the setup file through VirusTotal; it didn't detect anything:

![virustotal](https://user-images.githubusercontent.com/9217349/31172931-d55af682-a905-11e7-9152-0580c377fa21.png)
