### ISSUE TITLE
New version available leads to wrong download page

### ISSUE THREAD

**Issue by vascopimenta** [yishn/Sabaki#290]
When one clicks on the "Update" button, in the dialog box that informs a new version is available, the following page loads: https://api.github.com/repos/yishn/Sabaki/releases/latest.

This behaviour usually led to the list of available donwloads for the latest version: https://github.com/yishn/Sabaki/releases/tag/v0.31.4

This problem occurred already at least in the previous version.
Chrome 61.0.3163.100 on OS X 0.13 (High Sierra).

**Comment by yishn** [comment]
Thank you for your report!

**Comment by vascopimenta** [comment]
This has cropped up again.

**Comment by yishn** [comment]
I assume you just upgraded to v0.31.5 from v0.31.4. The bug was present in v0.31.4 when you reported it and has been fixed since, so this should be resolved in the new version v0.31.5, 😃

**Comment by vascopimenta** [comment]
True indeed. Apologies.
