### ISSUE TITLE
How about support multilanguage?

### ISSUE THREAD

**Issue by Heiseikiseki** [yishn/Sabaki#300]
HI, is there any plan to support mulch-language ?
I can help for translation.

**Comment by yishn** [comment]
It's not planned yet and needs quite a bit of programming work done before the translation work can begin. This is still Zukunftsmusik.

**Comment by yishn** [comment]
It's not planned yet and needs quite a bit of programming work done before the translation work can begin. This is still far in the future, so I'm going to close this for now.
