### ISSUE TITLE
engine games as black start too quickly

### ISSUE THREAD

**Issue by CamWagner** [yishn/Sabaki#302]
It's hard to set up a bot to play with the GTP time_settings command, if the bot is black. The bot immediately starts thinking, sometimes for 30-60 seconds, when the time_settings I want would be about 5 seconds per move. Is there a way to set the time settings inside the bot-management page? That way I could default some bots to think for a set amount of time (eg one bot named Leela 5s, another named Leela 10s)...

**Comment by yishn** [comment]
No, there is no standard way to configure time settings via GTP. Normally, you have to use a command line argument or a special GTP command. Please consult the documentation of the engines.
