### ISSUE TITLE
Sabaki exits out of autoplay mode after the first pass when two bots play

### ISSUE THREAD

**Issue by saweiss** [yishn/Sabaki#304]
I am using version 0.31.5 of Sabaki on MacOS High Sierra 10.13.1. When I was playing Leela Zero against IdiotBot, I noticed that the autoplay would stop after Leela Zero passed. Normally, this wouldn't be much of a problem if the pass were at the proper end of the game. However, Leela Zero often passes early because it is still in the early learning stages. So, the only thing I can do to keep the game going is to click "Attach" again.

At first I thought it was one of the bots, but the problem seems to be independent of which bot is used.

I tried glancing through the source code to see if anything stood out to me, but I haven't found anything yet. I will continue looking and learning more about how the project is set up. In the mean time, perhaps someone more knowledgeable can help find where the error is.

Thanks!

**Comment by yishn** [comment]
That's right, currently Sabaki will stop generating moves if one of the bots passes. Ideally, Sabaki should only stop after two consecutive passes.

**Comment by saweiss** [comment]
Thanks for the fix!
