### ISSUE TITLE
show full branch(serial stones with number) on board

### ISSUE THREAD

**Issue by wjx0912** [yishn/Sabaki#306]
hi, yishn,
in leela, we can get serial stones on every branch, as follow: 
http://image.weiqiba.com/github/question2.png

so can sabaki add branch function: http://image.weiqiba.com/github/question3.png

when select the first position, the board show serial stones(in current line) on board?
thank you~

**Comment by yishn** [comment]
Check out [LeelaSabaki](https://github.com/yishn/LeelaSabaki).
