### ISSUE TITLE
Engine passes don't get passed on to opponent engine

### ISSUE THREAD

**Issue by saweiss** [yishn/Sabaki#307]
I am using version 0.31.5 of Sabaki (compiled from the latest source code) on MacOS High Sierra 10.13.1. Now that #304 is fixed, I noticed that after one bot passes at the end of a game, the other bot tries to play illegal moves. A prompt pops up to warn me. The issue appears to be independent of the bots. Could this be because the bot "thinks" the board is blank, yet the display is kept the same?

**Comment by yishn** [comment]
Thanks for testing! I can't imagine why the bot would think the board is empty, do you see some clear board command in the GTP console? Unfortunately, it's hard for me to test this, since I don't have any bots which passes in the middle of the game...

**Comment by yishn** [comment]
I'm closing this since OP hasn't answered

**Comment by sp522** [comment]
I've seem something similar with GNUGo 3.8 vs Pachi 11.0
After the first GNUGo pass, Pachi exits with "Fatal: Non-alternating play detected".

From the log file, it seems like Pachi doesn't gracefully handle the back to back genmove calls of the same color.  Unsure if this is Sabaki's responsibility to make passes observable to the other side (bot or manual mode).  But making it observable with a "play color pass" to the other side seems more robust for these situations.
