### ISSUE TITLE
Sabaki v0.31.5 doesn't work from Leela on ubuntu

### ISSUE THREAD

**Issue by Philip2010** [yishn/Sabaki#308]
When I attach Leela 0.11.0 engine to Sabaki v0.31.5, Opening the GTP console shows that the program has not played. Could you please help me solve the problem.Thank you!

**Comment by yishn** [comment]
Please provide more information. Did you specify the correct arguments? How did you attach the engine? What error does the GTP console show?

**Comment by Philip2010** [comment]
I attach the engine with path "/Leela/leela_0110_linux_x64_opencl","--gtp", the GTP console windows shows not a word. The same problem when I attach Ray. While AQ works fine.Thank you.

**Comment by Philip2010** [comment]
When I run the *.AppImage file, the mate shows some error:
![2017-12-04 22-55-42](https://user-images.githubusercontent.com/34240393/33559039-84041c7a-d946-11e7-8a38-5785c2ae8a7a.png)

**Comment by yishn** [comment]
Can you try pressing <kbd>F5</kbd> after attaching the engine to force a move generation? What error does the GTP console show? If there's still nothing, [activate debug mode](https://github.com/yishn/Sabaki/blob/master/docs/guides/debugging.md) and look if there are any error messages in the Javascript Console.

**Comment by Philip2010** [comment]
F5 does't work. GTP console just shows nothing when I attach the engine.I will try debug mode,thank you!

And I find Rn requires CNTK.

"Require
-------
- CNTK version 2.0 Beta 12
  https://github.com/Microsoft/CNTK/releases"

I wonder if the error's due to I don't install CNTK.

**Comment by Philip2010** [comment]
I can't activate debuge mode. I run *.AppImage and can't find   $XDG_CONFIG_HOME/Sabaki or ~/.config/Sabaki on Linux.

"First, determine where Sabaki saves its settings:

    %APPDATA%\Sabaki on Windows
    $XDG_CONFIG_HOME/Sabaki or ~/.config/Sabaki on Linux
    ~/Library/Application Support/Sabaki on macOS"

**Comment by Philip2010** [comment]
I find the reason. Because I don't make the engine file a+x. Sorry for taking your time. Thank you.

**Comment by yishn** [comment]
No problem 😄 Glad you got it fixed.
