### ISSUE TITLE
Can you make sabaki support time_settings command?

### ISSUE THREAD

**Issue by kityanhem** [yishn/Sabaki#310]
I play against Leela Zero, it's always set 50s (default). I need to wait after it play a move and command time_settings in Toggle GTP console. It's really inconvenience. And if I make two bots play against each other, I can't change the time setting.

**Comment by yishn** [comment]
I'Leela (Zero) doesn't have a command line argument for time settings? I think the best solution here would be to add a command line argument, not to change something on Sabaki's side.

**Comment by roy7** [comment]
For now you have to send the time_settings commands via the GTP console. I found a prior bug that was fixed specifically about that https://github.com/yishn/Sabaki/issues/235.

Sabaki should have some sort of interface to the human for time controls, which will then send proper time_settings and time_left commands through GTP to a connected engine. That's the standard way to set and control time over GTP after all.

**Comment by zhu-jz** [comment]
Leela doesn't have a command line argument for the time settings, and gcp once said, (from https://github.com/gcp/leela-zero/issues/4)

> time_settings is a GTP command, not a command-line option. It has to be sent by the GTP interface. This is actually specifically pointed out in the README, "Usage" section. Configuring the time control for a GTP engine on the engine command-line is something that cannot possibly work correctly with the GTP protocol, and it's a mystery to me why some other engines even allow it.

**Comment by yishn** [comment]
In the new version Sabaki v0.33.0, you can specify GTP commands that will be sent to the engine right after attaching, so I'm closing this issue.

**Comment by as0770** [comment]
The specified gtp command is sent before all other gtp commands. So it won't work with most engines. A posibility to set the time for gtp engines would be extremely helpful. Maybe an option in the global preferences like "Time for gtp engines" or even better for each engine.

**Comment by yishn** [comment]
Why won't it work with most engines? It's perfectly valid, GTP-wise.

**Comment by as0770** [comment]
I guess they expect the usual initialization commands first, first the UI has to know which commands are supported before sending one to an engine.

This is the sequence sent by GoGui with every engine start, this is kind of a standard I guess:

name
= OnePunchGo

protocol_version
= 2.0

version
= 1.0

list_commands
= protocol_version name version known_command list_commands quit boardsize clear_board komi play genmove undo time_settings time_left opg_parameters 

boardsize 19
=

clear_board
=

komi 6.5
=

Sending other gtp commands after that should work well.

**Comment by yishn** [comment]
For the record, if a GTP engine can't handle `time_settings` before `komi` or `boardsize` or `clear_board` then it's most likely a bug on their end. But I guess Sabaki can send the engine-specific GTP commands after the initialization commands. Could you please open a new issue for this?
