### ISSUE TITLE
Add a horizontal layout to maximize the board size

### ISSUE THREAD

**Issue by animalize** [yishn/Sabaki#311]
Is it possible to move menu bar and bottom bar to the side of the board?
It will maximize the board size without lossing any convenience.

![a_new](https://user-images.githubusercontent.com/11244865/33793819-1bcb63e0-dcfa-11e7-9b6d-75648857c5e6.PNG)

**Comment by yishn** [comment]
You can hide the menu bar in the View menu, but moving the bottom bar to the side is not possible.

**Comment by ParmuzinAlexander** [comment]
Possible delete bottom bar.
main {
bottom: 0;
}
#bar {
visibility: hidden;
}
