### ISSUE TITLE
Can't save LeelaSabaki files

### ISSUE THREAD

**Issue by CamWagner** [yishn/Sabaki#313]
After generating long games with many variations in LeelaSabaki, Sabaki sometimes only saves one move and will not allow me to save the rest. Example output:

(;B[qo]AP[Sabaki:0.32.0]CA[UTF-8]
)

In this game, the first move was actually B[pp]. Also, the output should contain the header before the moves, like:

(;GM[1]FF[4]CA[UTF-8]AP[Sabaki:0.32.0]KM[7.5]SZ[19]DT[2017-12-13]
;B[pp]
)

Plus, the rest of the 200 moves are not there. Version is Sabaki v0.32.0 beta.

**Comment by yishn** [comment]
Thanks for the report!
