### ISSUE TITLE
Toggle color in edit mode

### ISSUE THREAD

**Issue by sheim** [yishn/Sabaki#314]
When in Edit Mode, and with Select Tool set to Stone Tool, as far as I can tell you have to click on the stones at the bottom to change colour. It would be very convenient if the same hotkey `Cmd+1` (in macOS, I'm assuming `ctrl+1` on other OSs) could also toggle the colour.

**Comment by yishn** [comment]
You're right, <kbd>Ctrl/Cmd+1</kdb> should toggle edit tool state as well. In the meantime, you can place a stone with the opponent's color with a right click.

**Comment by sheim** [comment]
Aha I see! yes that solves it, I just didn't figure it out : P
