### ISSUE TITLE
Sabaki can't be typed the command while bot vs. bot  is in process

### ISSUE THREAD

**Issue by Tsun-hung** [yishn/Sabaki#317]
I  can only type a command for one bot, the another one can't be change setting. For example, I set the time for one bot, when the new game begins, another bot run immediately so I can't do anything except quiting.
Can add a  margin time when a new game starts?

**Comment by yishn** [comment]
Just set time after the game starts; is that a problem?

**Comment by Tsun-hung** [comment]
@yishn It takes a long time if the playout is a large number ^_^.Another problem,how to continue the game after pause?

**Comment by yishn** [comment]
In the menu, choose 'Engines' > 'Generate Move', or just press <kbd>F5</kbd>. 

I guess we can add an option in the Preferences drawer whether to start generating moves immediately after attaching or not.

**Comment by Tsun-hung** [comment]
@yishn TYVM!  your idea is not bad!
