### ISSUE TITLE
confused by the new feature added in this version(Sabaki v0.33.0)

### ISSUE THREAD

**Issue by Tsun-hung** [yishn/Sabaki#318]
I noted that description, but don't know what is different in showing the heatmap between this version and the previous. I mean that the engines can show the heatmap in GTP console  in the previous version, and in this version, I can't find the option to visualizes the heatmap.
Another problem, where is the option whether Sabaki should start a game right after attaching engines?

**Comment by yishn** [comment]
In the new version, running the `heatmap` command in [LeelaSabaki](https://github.com/yishn/LeelaSabaki) will produce an actual heatmap on the board. Additionally, with the `--heatmap` option, you can let LeelaSabaki automatically generate a heatmap after each generated move.

The new option is located under 'Preferences', under the 'General' tab, the checkbox in the left column.

**Comment by Tsun-hung** [comment]
so I have to download and Install LeelaSabaki, right?

**Comment by yishn** [comment]
If you want to have heatmaps and variations of Leela integrated in Sabaki, yes.

**Comment by Tsun-hung** [comment]
Thanks!
