### ISSUE TITLE
Markups CANNOT mark on Stones! in v0.33.0.

### ISSUE THREAD

**Issue by meatgaga** [yishn/Sabaki#319]
Even using Default Theme, Markups such as "cross","triangle","square“and”circle“ cannot be marked on the stones, but can be marked on the board.  "letters" and "numbers" has not such issue. Please Check!
sry for my bad english! 
PS: Your Name sims you are Chinese, so i wrote it in CN once more...
在v0.33.0版本中，即使使用默认主题，”交叉“、”三角“、”方形和“圆形”标记也无法标记在棋子之上。但可以标记在棋盘上。“数字”和“字母”则没有这个问题。

**Comment by yishn** [comment]
Thanks for the report!

**Comment by fohristiwhirl** [comment]
Looks like they're in the SGF but not getting displayed.

**Comment by yishn** [comment]
@fohristiwhirl Yes, there's a problem with the CSS
