### ISSUE TITLE
Hoshi color

### ISSUE THREAD

**Issue by ParmuzinAlexander** [yishn/Sabaki#320]
In v0.33.1 hoshi color changed .goban .row li.hoshi::after to .goban .row li.hoshi::before? Need fix all themes?

**Comment by fohristiwhirl** [comment]
I noticed this too actually.

**Comment by yishn** [comment]
That's weird, I don't remember changing something like this... 😅

**Comment by yishn** [comment]
I'll try to see if I can revert the selector... But maybe we have to think about a long term solution.

**Comment by yishn** [comment]
It seems I can change the CSS selector back to `::after` for hoshi points, so you don't have to change anything. 👍 It will be fixed in the next release.

**Comment by yishn** [comment]
It seems that I can safely change the CSS selector back to `::after`, so you don't have to change anything 👍. It will be fixed in the next release.
