### ISSUE TITLE
npm run dist:linux fails 

### ISSUE THREAD

**Issue by JDJoe** [yishn/Sabaki#321]
Hello 
running: 
`npm run dist:linux `

fails 

Result is here: https://pastebin.com/d1E3Hrnt

Thank you

**Comment by yishn** [comment]
I believe you need to install `libicns`, `libicns-utils`, and maybe `GraphicsMagick`. They are dependencies of `electron-builder`.

**Comment by JDJoe** [comment]
OK, thank you. I had none of those installed.
