### ISSUE TITLE
How can I make Sabaki to wait for engine initializing?

### ISSUE THREAD

**Issue by beremaran** [yishn/Sabaki#322]
Hi,
Engine uses TensorFlow and it needs some time to initialize itself (tensorflow). When I attach engine to Sabaki, it is immediately sending commands resulting with no response.

How can I make Sabaki to wait for engine initializing?

for example;
```
● bGo> name 
…
● bGo> version 
…
● bGo> protocol_version 
…
● bGo> list_commands 
…
```

Thanks in advance.

**Comment by yishn** [comment]
You can't. Controllers have no way to tell if an engine is 'initialized'. Engines should be ready to receive commands from the get go. They can send responses when they are ready.
