### ISSUE TITLE
How do you clear cached settings in the web version?

### ISSUE THREAD

**Issue by nlpguyz** [yishn/Sabaki#326]
For the desktop version, I could remove $HOME/.config/Sabaki to clear settings. However, I am not sure how to do so in the web version. Can you please provide some insights?

Thanks!

**Comment by yishn** [comment]
In the web version, Sabaki saves its settings in local storage. If you're using Chrome, you can delete that by opening developer tools and click on 'Clear site data' from the 'Application' tab.
