### ISSUE TITLE
Show SGF game comments in the Game Info GUI, perhaps initially hidden under a "Show" button.

### ISSUE THREAD

**Issue by wctgit** [yishn/Sabaki#329]
Games generated by Leela Zero (especially self-play games) include some information about the game in a game-level comment. Of course, other sources of games might also include game-level comments. Indeed, the users themselves might wish to add or modify game-level comments to any game/SGF file.

That information/interface is not currently accessible through Sabaki (v0.33.1). A natural place to include this information would be within the game's Info pop-up GUI, along with Name, Date, Result, etc.

Comments might be long, so perhaps a multi-line text box could be used, perhaps with an as-needed vertical and/or horizontal scroll bar. Or, if auto-wrap is used, just an as-needed vertical scroll bar.

Since comments might contain game 'spoilers', perhaps they should be hidden by default with a Show button to display them.

An option could be added to the default settings to change this default behaviour, such as an "Always show game comments" checkbox under General preferences, which is off by default. Or, conversely, a "Hide game comments by default" checkbox which is on by default. Whichever makes more sense.

**Comment by yishn** [comment]
What game level comment? Can you provide a sample SGF file?

**Comment by wctgit** [comment]
In the current implementation of Leela Zero, below is an example. However, I am about to add a request for the Leela Zero project to include additional details, such as the time at which the game was played (since many sgfs are generated each day), so there may be even more human-readable information in the future:
>C[Leela Zero options: -p 1600 -r 1 -m 30 -t 1 -d -n --noponder -s 4907855558971854410 -g -q -w d9a5ed4897bca5499bcec21cdeadb0d180d9e0879be35af7de322537d666d75e]

[2f2b33b4fad44ea98cf5c4a22e34cf7e.zip](https://github.com/yishn/Sabaki/files/1670279/2f2b33b4fad44ea98cf5c4a22e34cf7e.zip)

**Comment by fohristiwhirl** [comment]
This seems to just be a comment in the root note. Sabaki shows it perfectly well.

**Comment by wctgit** [comment]
Ah, I was missing the Show Comments option in View menu. I was instead looking under the Info option of the 'hamburger' menu button on the lower right.

**Comment by yishn** [comment]
I'm closing this since this issue seems to be resolved.
