### ISSUE TITLE
ASCII Diagram omits stones

### ISSUE THREAD

**Issue by agentneigh** [yishn/Sabaki#330]
Any stone with a special character like "a"
or "b"
are omitted on this.
Can you please have it fill with regular stones.
Thank you :)

**Comment by yishn** [comment]
What do you mean? Can you provide a sample SGF file that reproduces this issue?

**Comment by agentneigh** [comment]
Agent Neigh:
`$$
$$ +---------------------------------------+
$$ | . . . . . . O . X O . X . . . . . . . |
$$ | . . . . . . O . X O . X . . . . . . . |
$$ | . . . . . . O . X O . X . . . . . . . |
$$ | . . . , . . . O O X X . . . . , . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . , . . . . . , . . . . . , . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . , . . . . . , . . . . . , . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ +---------------------------------------+`
Above is a clipboard copy from sabaki.
If a stone has a special cbaracte such as an a or triangle the stone will
be removed from the diagram entirely.
Agent Neigh:
`$$
$$ +---------------------------------------+
$$ | . . . . . . O . X O . X . . . . . . . |
$$ | . . . . . . O . X O . X . . . . . . . |
$$ | . . . . . . O . X O . X . . . . . . . |
$$ | . . . , . . . O O . . . . . . , . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . , . . . . . , . . . . . , . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . , . . . . . , . . . . . , . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ | . . . . . . . . . . . . . . . . . . . |
$$ +---------------------------------------+`
The above would be an example of two stones missing because of a special
characters on the stone.
