### ISSUE TITLE
Empty SGF tree causes repeated exceptions

### ISSUE THREAD

**Issue by fohristiwhirl** [yishn/Sabaki#57]
After opening a file with the following contents (2 bytes):

()

There are repeated warnings about uncaught exceptions (every time you click the board).

**Comment by yishn** [comment]
`()` is not a valid SGF file since it has a game tree which has no nodes. Internally, Sabaki allows zero nodes game trees for game collections, but assumes that actual game trees has nodes.

**Comment by fohristiwhirl** [comment]
Agree - still ideally bad files would probably not put the program into an unusable state.
