### ISSUE TITLE
Editing compressed point lists for AB/AW/AE doesn't work

### ISSUE THREAD

**Issue by fohristiwhirl** [yishn/Sabaki#58]
Consider this:

(;AB[dd:gg])

Although Sabaki can read this and display the board correctly, editing it with the AB or AW tools doesn't work. In fact one ends up with a file with conflicting AB/AW/AE properties.

Note that, although editing compressed *AW* lists seems to work, the SGF file is just as conflicted, and I guess it only looks OK because of the order in which Sabaki evaluates the properties.

I'm afraid you probably have to decompress such lists. I notice you do this for marks such as MA, TR, etc when edited, so hopefully it's not too much trouble.

**Comment by yishn** [comment]
Thanks!
