### ISSUE TITLE
Consider handling old SGF with lowercase "long properties"

### ISSUE THREAD

**Issue by fohristiwhirl** [yishn/Sabaki#68]
Very old SGF files sometimes have lowercase letters in the property names which should be discarded, e.g. one might see:

(;GaMe[1]SiZe[9]PlayerBlack[Miyamoto Naoki]PlayerWhite[Go Seigen]DaTe[1968]REsult[B+4];Black[de];White[fe])

By discarding all the lowercase letters in the property names we can get the Right Thing.

For some real world examples see:
* http://www.kolumbus.fi/karppinen.ari/lp-ol-01.sgf
* http://www.yutopian.com/go/Jigo/games/game498.sgf

Currently Sabaki doesn't handle these.

**Comment by yishn** [comment]
Shouldn't be a problem, this seems to be compatible with SGF FF[4].
