### ISSUE TITLE
SGF Parsing for backslashes in comments

### ISSUE THREAD

**Issue by yewang** [yishn/Sabaki#69]
It seems that the SGF parser may fail on certain edge cases:

`(;C[\];B[aa];W[bb])`
Two nodes: comment `];B[aa` in root node, white move in second node

`(;C[\\];B[aa];W[bb])`
Three nodes: comment `\` in root node, black move in second node, white move in third node

`(;C[\\\];B[aa];W[bb])`
Two nodes: comment `\];B[aa` in root node, white move in second node

`(;C[\\\\];B[aa];W[bb])`
Three nodes: comment `\\` in root node, black move in second node, white move in third node

**Comment by yishn** [comment]
Thanks! Seems to be a problem with the tokenizer...
