### ISSUE TITLE
Crash on startup after computer freezing

### ISSUE THREAD

**Issue by TheIronMarx** [yishn/Sabaki#73]
Hello! I was reviewing a game in Sabaki when my computer hard froze and I had to reboot. When I tried to resume my review, I'm presented with a vague exception thrown instead.

As I've seen in #70, this also doesn't close the application properly and I need to close the process from the process manager. I am running Windows 8.1.

http://sli.mg/1ljNGA

**Comment by yishn** [comment]
This is pretty vague... Have you tried running a freshly downloaded Sabaki? You could also try deleting the `Sabaki` folder in `%APPDATA%`, resetting all settings of Sabaki.

**Comment by TheIronMarx** [comment]
I'll give it a shot later this evening and report back.

**Comment by TheIronMarx** [comment]
There is no Sabaki folder in %APPDATA%. That probably has something to do with it.

**Comment by TheIronMarx** [comment]
No, I misspoke. Wrong disk. My apologies. Finding and deleting the Sabaki folder in %APPDATA% fixed the issue.
