### ISSUE TITLE
Graphics in 0.12.3

### ISSUE THREAD

**Issue by fohristiwhirl** [yishn/Sabaki#74]
The graphics seem to have gotten a lot worse in 0.12.3 - the anti-aliasing that was present in the PNG files doesn't seem to work very well out of the SVG; also the shadows seem to be mostly gone...

I think maybe the shadows are hidden by the fact that the stones have become slightly bigger? Not sure.

**Comment by yishn** [comment]
CSS is handling shadows now.

**Previous:**

![Previous](https://raw.githubusercontent.com/yishn/Sabaki/0e86cd5f2d54126937d30b7defd239e2cdd37666/screenshot.png)

**Now:**

![Now](https://raw.githubusercontent.com/yishn/Sabaki/master/screenshot.png)

I wouldn't say the shadows are gone, maybe they're a little more subtle? I wouldn't say there's no anti-aliasing at all, but the images are less blurry and more crisp? I think it's just a matter of taste. I don't think the stones have gotten bigger...

If you want to, you can try tweaking the CSS shadow settings and report back what you personally find best. You can find the corresponding statements [here](github.com/yishn/Sabaki/blob/master/style/goban.css#L45-L46).

**Comment by yishn** [comment]
Letting CSS handling shadows and using SVG images has the following benefits:

* Board is now infinitely scalable and nothing will get blurry
* You can replace stone images with other stone images that have no shadows
* Smaller and more easily editable files

**Comment by fohristiwhirl** [comment]
Here's an in-place comparison:

http://imgur.com/olDvBO2

The anti-aliasing issue doesn't really show because imgur is scaling (and thus blurring the image)...

**Comment by fohristiwhirl** [comment]
Here's a better example, scaled up 2000%:

http://imgur.com/6v0acZe

**Comment by yishn** [comment]
I retract my statement about the stones not being bigger, but I'm not quite sure what you want to say with the images. The stones are anti-aliased and have a (subtle) shadow.

**Comment by fohristiwhirl** [comment]
Hmm. I wonder if anyone else is following this and can give an opinion.

**Comment by yishn** [comment]
I have made png equivalents of the current svg images and compared them side by side at 200% and now I think I see what you mean. I haven't noticed it till now; for some reason Chrome just doesn't do enough anti-aliasing on svg images.

Furthermore, I reinforced the shadow on the black stones, what do you think about this?

![unbenannt](https://cloud.githubusercontent.com/assets/9217349/14970821/7e92005c-10cc-11e6-8938-649232e151c7.png)

**Comment by fohristiwhirl** [comment]
That seems much better than 0.12.3.

**Comment by yishn** [comment]
This is fixed in v0.12.4.
