### ISSUE TITLE
Add setting for showing 'sibling' style variations

### ISSUE THREAD

**Issue by yewang** [yishn/Sabaki#77]
It seems that the variations style property "ST" is ignored (defaulting to always showing variations in "children" style). This property toggles whether variations are shown, as well as whether variations are shown in "children" style or "sibling" style.

See:
http://www.red-bean.com/sgf/properties.html#ST

**Comment by yishn** [comment]
I'm very opinionated on this issue. I think the user should decide for himself (and make these changes himself) how they want to display variations. A SGF file should **never** alter the behavior of the client. I'm afraid this 'feature' will never be implemented in Sabaki.

Another question is whether there should be a setting whether to show the variations in 'children' or 'sibling' style (regardless of the `ST` property). I think this could be considered.

**Comment by yewang** [comment]
> I think the user should decide for himself (and make these changes himself) how they want to display variations.

I agree, and if the user choose to change the style, the ST property should just be appropriately updated. The ST property just chooses the default on load, but shouldn't prevent the user from changing it as they see fit.

However, this property is useful since the authors of SGFs containing game reviews may make comments about variations in "children" style vs "sibling" style.

The SGF standard discusses this more here:
http://www.red-bean.com/sgf/user_guide/#variations

**Comment by yishn** [comment]
I'm well aware of the `ST` property in the SGF standard. Still, even when the user can change the style back, I think it is a very bad idea to open a SGF file and changing the variation display style without the user knowing or agreeing.

**Comment by yewang** [comment]
Why can't the interface just notify the user or otherwise make it clear whether it is in "sibling" or "child" style? That is a question of interface design, not an argument for excluding support for "sibling" style variants altogether.

I think it's even worse to force players to use only "child" style variations, especially for viewing existing SGF files that have already been composed using comments on "sibling" style variations.

**Comment by yishn** [comment]
I said it's fine to provide a setting for sibling style variations, but Sabaki won't change the setting arbitrarily when loading files. That's also why I kept this issue open. I already stated my reasons for this decision above. Also I'm not forcing anyone to do anything really.
