### ISSUE TITLE
Higher digit number labels are truncated

### ISSUE THREAD

**Issue by yewang** [yishn/Sabaki#78]
It would be nice to be able to enter custom and/or duplicate labels, as opposed to the current cyclical label behavior. Also, it would nice if three-digit number labels weren't truncated (e.g., "1...") since three-digit labels are sometimes used in SGFs when marking stones with their move number.

**Comment by yishn** [comment]
Three-digit number labels work fine here:

![unbenannt](https://cloud.githubusercontent.com/assets/9217349/14993548/973d18f4-116b-11e6-93b5-57f05990060d.png)

**Comment by yewang** [comment]
Sorry, I forgot to clarify that I observed this issue on the web version.

**Comment by yishn** [comment]
These also work here, in Chrome at least:

![unbenannt](https://cloud.githubusercontent.com/assets/9217349/14993961/a63019e0-116d-11e6-9843-3c7a1ee52a4f.png)

**Comment by yewang** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1282466/14994059/d06a757a-113b-11e6-8cd0-8e1bdb33eba8.png)

Observed this on Firefox

Here's the SGF file
`(;B[aa]LB[aa:100][bb:100])`

**Comment by yishn** [comment]
It works fine in Firefox here as well. I suspect it has something to do with the font and how the font width is larger in your OS. I have no way to test this properly. Can you possibly open dev tools on your end and adjust the font size till everything is visible? The element in question is:

    .goban .row li.smalllabel .stone span::before

I really appreciate your help!

**Comment by yishn** [comment]
I'm moving 'Custom Labels' to #79.

**Comment by yewang** [comment]
Changing the font size successfully makes the label smaller, however, the issue still appears.

![screenshot-2](https://cloud.githubusercontent.com/assets/1282466/14995550/55114c84-1143-11e6-8f40-8c96529b8033.png)

Weird new observation. I can make the issue go away by resizing the board (via the resizers or changing the window size). The issue comes and gos at various board sizes. This happens even at default, larger, and smaller font sizes.

I can make the issue go away even for a larger font by changing the board until it looks fine:
![screenshot-3](https://cloud.githubusercontent.com/assets/1282466/14995552/551a1242-1143-11e6-9218-3fdf45b517eb.png)
but as I resize the board the issue comes in and out (i.e., not truncated at some arbitrary board sizes, but truncated at others).

**Comment by yishn** [comment]
Sorry, I forgot that the width depends on the font size... So what you really need to adjust is the width of:

    .goban .row li.smalllabel .stone span::before

The labels will be off-center when you change the widths; I will correct them.

**Comment by yishn** [comment]
I've resolved this and #76 in a more stable way. Thank you for your help anyway!
