### ISSUE TITLE
Game Date visible 

### ISSUE THREAD

**Issue by TheIronMarx** [yishn/Sabaki#81]
I would like to be able to see the date of a game played in the info window. There is support for it in SGF, the `DT` key. It would be cool to be able to see that at a glance. Currently, I have the habit of writing the date in the chat log, but the info window would be nice, too.

**Comment by yishn** [comment]
Creating a user-friendly date picker for all of the different cases specified in the [SGF standard](http://red-bean.com/sgf/properties.html#DT) seems a little tricky. 

Do you have a concrete idea what you'd like to have? Like:

* How to edit dates
* How to display dates

**Comment by fohristiwhirl** [comment]
In reality DT fields out there can often violate the standard. For example, I'm looking at a file now that has:

DT[1842-03-30 (Tenpo 13 II 19)]

Personally I just allow arbitrary text in the date field in my SGF editor...

**Comment by TheIronMarx** [comment]
Well it's too bad the DT isn't or hasn't been more strictly enforced. @yishn, at the very least I'd like to see the string literal contained in the DT field. If the standard hasn't been enforced, then don't worry about translating it into a different format. Just let me see the string. I'm sure it will be fine. If it isn't, you know, whatever! 

I believe that editing the date field would also be fine and desirable. In that case, I say do whatever implementation is easiest, but adamantly adhere to the SGF spec.
