### ISSUE TITLE
Add support for boardsizes that are really small

### ISSUE THREAD

**Issue by levelonedev** [yishn/Sabaki#84]
I would like to use your program to test and play against the AI I am making. In order to have really quick games it's often helpful to play 5x5 or smaller games.

**Comment by yishn** [comment]
In the meantime, you can open SGF files with small board sizes in Sabaki to create a small board. Just copy the following snippet and load it in Sabaki by clicking 'File' > 'Load From Clipboard'.

~~~
(;GM[1]KM[6.5]SZ[5])
~~~

If your window gets too big though, the grid lines becomes weird.
