### ISSUE TITLE
Unable to attach engines

### ISSUE THREAD

**Issue by cmacht** [yishn/Sabaki#92]
I feel a bit lost figuring out how I can use Sabaki to play go against a computer (e.g. use Sabaki as an interface for a "Go Engine").

First of all, it would be really useful to have a list of recommended (compiled) engines that work. I went ahead and after some searching (http://senseis.xmp.net/?GoTextProtocol) downloaded these:

- GNU Go: http://www.gnu.org/software/gnugo/download.html
- Indigo: http://www.math-info.univ-paris5.fr/~bouzy/INDIGO.html

Unfortunately, when I try to "Attach" them in Sabaki, I get the following error:

> Sabaki v.0.14.0
> Something weird happened. Sabaki will shut itself down.
> If possible, please report this on Sabaki’s repository on GitHub.

Any help much appreciated!

**Comment by yishn** [comment]
Could you post your OS and your engine configurations? Some engines need a special argument for going into GTP mode (GNU Go needs `--mode gtp`).

**Comment by cmacht** [comment]
Thanks for responding!

I'm on MacOS X 10.11.5 and I'm using GNU Go 3.6 (if you could point me to / upload a more recent compiled version, that would be much appreciated).

I didn't know about the arguments, tried it both with without "--" (two preceding dashes) – but to no avail, same error as above keeps popping up.

![screen shot 2016-05-25 at 8 33 58 am](https://cloud.githubusercontent.com/assets/1307113/15530240/87246ed8-2253-11e6-8d0e-54db47713d36.png)

**Comment by yishn** [comment]
Did you compile GNU Go on Mac yourself? Could you check if it is working at all by running gnugo in the Terminal? As for Indigo, on its website it states that there's only a Linux release. Not sure if it works on OSX.

You can find working binaries of GNU Go for Mac on this site: http://www.sente.ch/software/goban3/#Download. Make sure you download **GNU Go 3.7.11 for Mac OS X 10.4.3 and above, universal binary** `gnugo-3.7.11.dmg`.

**Comment by cmacht** [comment]
Great! Thank you, it now works perfectly!

I didn't manage to compile GNU Go myself and something must have been wrong with the one I downloaded.

I added a page "Engines" to the wiki – obviously this only covers Mac OS for now.

**Comment by yishn** [comment]
Thank you for your work!
