### ISSUE TITLE
Avoid crashing when GTP engines do weird things

### ISSUE THREAD

**Issue by yishn** [yishn/Sabaki#93]

**Comment by cmacht** [comment]
As a reference, here's the GNU Go 3.6 crashing binary I downloaded from [this glGo mirror](http://www.pandanet.co.jp/English/glgo/download.html).

[gnugo-3.6-mac.zip](https://github.com/yishn/Sabaki/files/281350/gnugo-3.6-mac.zip)

**Comment by yishn** [comment]
I can't reproduce any crashing at all on master, so I assume this is already resolved.
