### ISSUE TITLE
Handicap Stones Not Showing

### ISSUE THREAD

**Issue by AnselAtoms** [yishn/Sabaki#96]
I created this sgf with Easy Go Lite on an iPad, and only one of the five handicap stones is showing. All five stones are shown in both Easy Go and Sente Goban.
[2016-05-29-02.sgf.txt](https://github.com/yishn/Sabaki/files/288957/2016-05-29-02.sgf.txt)

**Comment by yishn** [comment]
Quick investigation yields that the SGF file is invalid. In the first node, the property AB is specified multiple times. Since EasyGo 1.8.3 created this file, I suggest you report this issue to EasyGo.
